/PROG  PNS001.LS
/ATTR
OWNER       = MNEDITOR;
COMMENT     = "";
PROG_SIZE   = 636;
CREATE      = DATE 23-01-07  TIME 11:59:14;
MODIFIED    = DATE 23-01-07  TIME 12:02:18;
FILE_NAME   = ;
VERSION     = 0;
LINE_COUNT  = 4;
MEMORY_SIZE = 992;
PROTECT     = READ_WRITE;
TCD:  STACK_SIZE	= 0,
      TASK_PRIORITY	= 50,
      TIME_SLICE	= 0,
      BUSY_LAMP_OFF	= 0,
      ABORT_REQUEST	= 0,
      PAUSE_REQUEST	= 0;
DEFAULT_GROUP	= 1,*,*,*,*;
CONTROL_CODE	= 00000000 00000000;
/MN
   1:J P[1] 100% FINE    ;
   2:L P[2] 100mm/sec CNT0    ;
   3:L P[3] 100mm/sec CNT0    ;
   4:L P[4] 100mm/sec CNT0    ;
   5:L P[5] 100mm/sec CNT0    ;
   6:L P[6] 100mm/sec CNT0    ;
   7:L P[7] 100mm/sec CNT0    ;
   8:L P[8] 100mm/sec CNT0    ;
   9:L P[9] 100mm/sec CNT0    ;
   10:L P[10] 100mm/sec CNT0    ;
   11:L P[11] 100mm/sec CNT0    ;
   12:L P[12] 100mm/sec CNT0    ;
   13:L P[13] 100mm/sec CNT0    ;
   14:L P[14] 100mm/sec CNT0    ;
   15:L P[15] 100mm/sec CNT0    ;
   16:L P[16] 100mm/sec CNT0    ;
   17:L P[17] 100mm/sec CNT0    ;
   18:L P[18] 100mm/sec CNT0    ;
   19:L P[19] 100mm/sec CNT0    ;
   20:L P[20] 100mm/sec CNT0    ;
   21:L P[21] 100mm/sec CNT0    ;
   22:L P[22] 100mm/sec CNT0    ;
   23:L P[23] 100mm/sec CNT0    ;
   24:L P[24] 100mm/sec CNT0    ;
   25:L P[25] 100mm/sec CNT0    ;
   26:L P[26] 100mm/sec CNT0    ;
   27:L P[27] 100mm/sec CNT0    ;
   28:L P[28] 100mm/sec CNT0    ;
   29:L P[29] 100mm/sec CNT0    ;
   30:L P[30] 100mm/sec CNT0    ;
   31:L P[31] 100mm/sec CNT0    ;
   32:L P[32] 100mm/sec CNT0    ;
   33:L P[33] 100mm/sec CNT0    ;
   34:L P[34] 100mm/sec CNT0    ;
   35:L P[35] 100mm/sec CNT0    ;
   36:L P[36] 100mm/sec CNT0    ;
   37:L P[37] 100mm/sec CNT0    ;
   38:L P[38] 100mm/sec CNT0    ;
   39:L P[39] 100mm/sec CNT0    ;
   40:L P[40] 100mm/sec CNT0    ;
   41:L P[41] 100mm/sec CNT0    ;
   42:L P[42] 100mm/sec CNT0    ;
   43:L P[43] 100mm/sec CNT0    ;
   44:L P[44] 100mm/sec CNT0    ;
   45:L P[45] 100mm/sec CNT0    ;
   46:L P[46] 100mm/sec CNT0    ;
   47:L P[47] 100mm/sec CNT0    ;
   48:L P[48] 100mm/sec CNT0    ;
   49:L P[49] 100mm/sec CNT0    ;
   50:L P[50] 100mm/sec CNT0    ;
   51:L P[51] 100mm/sec CNT0    ;
   52:L P[52] 100mm/sec CNT0    ;
   53:L P[53] 100mm/sec CNT0    ;
   54:L P[54] 100mm/sec CNT0    ;
   55:L P[55] 100mm/sec CNT0    ;
   56:L P[56] 100mm/sec CNT0    ;
   57:L P[57] 100mm/sec CNT0    ;
   58:L P[58] 100mm/sec CNT0    ;
   59:L P[59] 100mm/sec CNT0    ;
   60:L P[60] 100mm/sec CNT0    ;
   61:L P[61] 100mm/sec CNT0    ;
   62:L P[62] 100mm/sec CNT0    ;
   63:L P[63] 100mm/sec CNT0    ;
   64:L P[64] 100mm/sec CNT0    ;
   65:L P[65] 100mm/sec CNT0    ;
   66:L P[66] 100mm/sec CNT0    ;
   67:L P[67] 100mm/sec CNT0    ;
   68:L P[68] 100mm/sec CNT0    ;
   69:L P[69] 100mm/sec CNT0    ;
   70:L P[70] 100mm/sec CNT0    ;
   71:L P[71] 100mm/sec CNT0    ;
   72:L P[72] 100mm/sec CNT0    ;
   73:L P[73] 100mm/sec CNT0    ;
   74:L P[74] 100mm/sec CNT0    ;
   75:L P[75] 100mm/sec CNT0    ;
   76:L P[76] 100mm/sec CNT0    ;
   77:L P[77] 100mm/sec CNT0    ;
   78:L P[78] 100mm/sec CNT0    ;
   79:L P[79] 100mm/sec CNT0    ;
   80:L P[80] 100mm/sec CNT0    ;
   81:L P[81] 100mm/sec CNT0    ;
   82:L P[82] 100mm/sec CNT0    ;
   83:L P[83] 100mm/sec CNT0    ;
   84:L P[84] 100mm/sec CNT0    ;
   85:L P[85] 100mm/sec CNT0    ;
   86:L P[86] 100mm/sec CNT0    ;
   87:L P[87] 100mm/sec CNT0    ;
   88:L P[88] 100mm/sec CNT0    ;
   89:L P[89] 100mm/sec CNT0    ;
   90:L P[90] 100mm/sec CNT0    ;
   91:L P[91] 100mm/sec CNT0    ;
   92:L P[92] 100mm/sec CNT0    ;
   93:L P[93] 100mm/sec CNT0    ;
   94:L P[94] 100mm/sec CNT0    ;
   95:L P[95] 100mm/sec CNT0    ;
   96:L P[96] 100mm/sec CNT0    ;
   97:L P[97] 100mm/sec CNT0    ;
   98:L P[98] 100mm/sec CNT0    ;
   99:L P[99] 100mm/sec CNT0    ;
   100:L P[100] 100mm/sec CNT0    ;
   101:L P[101] 100mm/sec CNT0    ;
   102:L P[102] 100mm/sec CNT0    ;
   103:L P[103] 100mm/sec CNT0    ;
   104:L P[104] 100mm/sec CNT0    ;
   105:L P[105] 100mm/sec CNT0    ;
   106:L P[106] 100mm/sec CNT0    ;
   107:L P[107] 100mm/sec CNT0    ;
   108:L P[108] 100mm/sec CNT0    ;
   109:L P[109] 100mm/sec CNT0    ;
   110:L P[110] 100mm/sec CNT0    ;
   111:L P[111] 100mm/sec CNT0    ;
   112:L P[112] 100mm/sec CNT0    ;
   113:L P[113] 100mm/sec CNT0    ;
   114:L P[114] 100mm/sec CNT0    ;
   115:L P[115] 100mm/sec CNT0    ;
   116:L P[116] 100mm/sec CNT0    ;
   117:L P[117] 100mm/sec CNT0    ;
   118:L P[118] 100mm/sec CNT0    ;
   119:L P[119] 100mm/sec CNT0    ;
   120:L P[120] 100mm/sec CNT0    ;
   121:L P[121] 100mm/sec CNT0    ;
   122:L P[122] 100mm/sec CNT0    ;
   123:L P[123] 100mm/sec CNT0    ;
   124:L P[124] 100mm/sec CNT0    ;
   125:L P[125] 100mm/sec CNT0    ;
   126:L P[126] 100mm/sec CNT0    ;
   127:L P[127] 100mm/sec CNT0    ;
   128:L P[128] 100mm/sec CNT0    ;
   129:L P[129] 100mm/sec CNT0    ;
   130:L P[130] 100mm/sec CNT0    ;
   131:L P[131] 100mm/sec CNT0    ;
   132:L P[132] 100mm/sec CNT0    ;
   133:L P[133] 100mm/sec CNT0    ;
   134:L P[134] 100mm/sec CNT0    ;
   135:L P[135] 100mm/sec CNT0    ;
   136:L P[136] 100mm/sec CNT0    ;
   137:L P[137] 100mm/sec CNT0    ;
   138:L P[138] 100mm/sec CNT0    ;
   139:L P[139] 100mm/sec CNT0    ;
   140:L P[140] 100mm/sec CNT0    ;
   141:L P[141] 100mm/sec CNT0    ;
   142:L P[142] 100mm/sec CNT0    ;
   143:L P[143] 100mm/sec CNT0    ;
   144:L P[144] 100mm/sec CNT0    ;
   145:L P[145] 100mm/sec CNT0    ;
   146:L P[146] 100mm/sec CNT0    ;
   147:L P[147] 100mm/sec CNT0    ;
   148:L P[148] 100mm/sec CNT0    ;
   149:L P[149] 100mm/sec CNT0    ;
   150:L P[150] 100mm/sec CNT0    ;
   151:L P[151] 100mm/sec CNT0    ;
   152:L P[152] 100mm/sec CNT0    ;
   153:L P[153] 100mm/sec CNT0    ;
   154:L P[154] 100mm/sec CNT0    ;
   155:L P[155] 100mm/sec CNT0    ;
   156:L P[156] 100mm/sec CNT0    ;
   157:L P[157] 100mm/sec CNT0    ;
   158:L P[158] 100mm/sec CNT0    ;
   159:L P[159] 100mm/sec CNT0    ;
   160:L P[160] 100mm/sec CNT0    ;
   161:L P[161] 100mm/sec CNT0    ;
   162:L P[162] 100mm/sec CNT0    ;
   163:L P[163] 100mm/sec CNT0    ;
   164:L P[164] 100mm/sec CNT0    ;
   165:L P[165] 100mm/sec CNT0    ;
   166:L P[166] 100mm/sec CNT0    ;
   167:L P[167] 100mm/sec CNT0    ;
   168:L P[168] 100mm/sec CNT0    ;
   169:L P[169] 100mm/sec CNT0    ;
   170:L P[170] 100mm/sec CNT0    ;
   171:L P[171] 100mm/sec CNT0    ;
   172:L P[172] 100mm/sec CNT0    ;
   173:L P[173] 100mm/sec CNT0    ;
   174:L P[174] 100mm/sec CNT0    ;
   175:L P[175] 100mm/sec CNT0    ;
   176:L P[176] 100mm/sec CNT0    ;
   177:L P[177] 100mm/sec CNT0    ;
   178:L P[178] 100mm/sec CNT0    ;
   179:L P[179] 100mm/sec CNT0    ;
   180:L P[180] 100mm/sec CNT0    ;
   181:L P[181] 100mm/sec CNT0    ;
   182:L P[182] 100mm/sec CNT0    ;
   183:L P[183] 100mm/sec CNT0    ;
   184:L P[184] 100mm/sec CNT0    ;
   185:L P[185] 100mm/sec CNT0    ;
   186:L P[186] 100mm/sec CNT0    ;
   187:L P[187] 100mm/sec CNT0    ;
   188:L P[188] 100mm/sec CNT0    ;
   189:L P[189] 100mm/sec CNT0    ;
   190:L P[190] 100mm/sec CNT0    ;
   191:L P[191] 100mm/sec CNT0    ;
   192:L P[192] 100mm/sec CNT0    ;
   193:L P[193] 100mm/sec CNT0    ;
   194:L P[194] 100mm/sec CNT0    ;
   195:L P[195] 100mm/sec CNT0    ;
   196:L P[196] 100mm/sec CNT0    ;
   197:L P[197] 100mm/sec CNT0    ;
   198:L P[198] 100mm/sec CNT0    ;
   199:L P[199] 100mm/sec CNT0    ;
   200:L P[200] 100mm/sec CNT0    ;
   201:L P[201] 100mm/sec CNT0    ;
   202:L P[202] 100mm/sec CNT0    ;
   203:L P[203] 100mm/sec CNT0    ;
   204:L P[204] 100mm/sec CNT0    ;
   205:L P[205] 100mm/sec CNT0    ;
   206:L P[206] 100mm/sec CNT0    ;
   207:L P[207] 100mm/sec CNT0    ;
   208:L P[208] 100mm/sec CNT0    ;
   209:L P[209] 100mm/sec CNT0    ;
   210:L P[210] 100mm/sec CNT0    ;
   211:L P[211] 100mm/sec CNT0    ;
   212:L P[212] 100mm/sec CNT0    ;
   213:L P[213] 100mm/sec CNT0    ;
   214:L P[214] 100mm/sec CNT0    ;
   215:L P[215] 100mm/sec CNT0    ;
   216:L P[216] 100mm/sec CNT0    ;
   217:L P[217] 100mm/sec CNT0    ;
   218:L P[218] 100mm/sec CNT0    ;
   219:L P[219] 100mm/sec CNT0    ;
   220:L P[220] 100mm/sec CNT0    ;
   221:L P[221] 100mm/sec CNT0    ;
   222:L P[222] 100mm/sec CNT0    ;
   223:L P[223] 100mm/sec CNT0    ;
   224:L P[224] 100mm/sec CNT0    ;
   225:L P[225] 100mm/sec CNT0    ;
   226:L P[226] 100mm/sec CNT0    ;
   227:L P[227] 100mm/sec CNT0    ;
   228:L P[228] 100mm/sec CNT0    ;
   229:L P[229] 100mm/sec CNT0    ;
   230:L P[230] 100mm/sec CNT0    ;
   231:L P[231] 100mm/sec CNT0    ;
   232:L P[232] 100mm/sec CNT0    ;
   233:L P[233] 100mm/sec CNT0    ;
   234:L P[234] 100mm/sec CNT0    ;
   235:L P[235] 100mm/sec CNT0    ;
   236:L P[236] 100mm/sec CNT0    ;
   237:L P[237] 100mm/sec CNT0    ;
   238:L P[238] 100mm/sec CNT0    ;
   239:L P[239] 100mm/sec CNT0    ;
   240:L P[240] 100mm/sec CNT0    ;
   241:L P[241] 100mm/sec CNT0    ;
   242:L P[242] 100mm/sec CNT0    ;
   243:L P[243] 100mm/sec CNT0    ;
   244:L P[244] 100mm/sec CNT0    ;
   245:L P[245] 100mm/sec CNT0    ;
   246:L P[246] 100mm/sec CNT0    ;
   247:L P[247] 100mm/sec CNT0    ;
   248:L P[248] 100mm/sec CNT0    ;
   249:L P[249] 100mm/sec CNT0    ;
   250:L P[250] 100mm/sec CNT0    ;
   251:L P[251] 100mm/sec CNT0    ;
   252:L P[252] 100mm/sec CNT0    ;
   253:L P[253] 100mm/sec CNT0    ;
   254:L P[254] 100mm/sec CNT0    ;
   255:L P[255] 100mm/sec CNT0    ;
   256:L P[256] 100mm/sec CNT0    ;
   257:L P[257] 100mm/sec CNT0    ;
   258:L P[258] 100mm/sec CNT0    ;
   259:L P[259] 100mm/sec CNT0    ;
   260:L P[260] 100mm/sec CNT0    ;
   261:L P[261] 100mm/sec CNT0    ;
   262:L P[262] 100mm/sec CNT0    ;
   263:L P[263] 100mm/sec CNT0    ;
   264:L P[264] 100mm/sec CNT0    ;
   265:L P[265] 100mm/sec CNT0    ;
   266:L P[266] 100mm/sec CNT0    ;
   267:L P[267] 100mm/sec CNT0    ;
   268:L P[268] 100mm/sec CNT0    ;
   269:L P[269] 100mm/sec CNT0    ;
   270:L P[270] 100mm/sec CNT0    ;
   271:L P[271] 100mm/sec CNT0    ;
   272:L P[272] 100mm/sec CNT0    ;
   273:L P[273] 100mm/sec CNT0    ;
   274:L P[274] 100mm/sec CNT0    ;
   275:L P[275] 100mm/sec CNT0    ;
   276:L P[276] 100mm/sec CNT0    ;
   277:L P[277] 100mm/sec CNT0    ;
   278:L P[278] 100mm/sec CNT0    ;
   279:L P[279] 100mm/sec CNT0    ;
   280:L P[280] 100mm/sec CNT0    ;
   281:L P[281] 100mm/sec CNT0    ;
   282:L P[282] 100mm/sec CNT0    ;
   283:L P[283] 100mm/sec CNT0    ;
   284:L P[284] 100mm/sec CNT0    ;
   285:L P[285] 100mm/sec CNT0    ;
   286:L P[286] 100mm/sec CNT0    ;
   287:L P[287] 100mm/sec CNT0    ;
   288:L P[288] 100mm/sec CNT0    ;
   289:L P[289] 100mm/sec CNT0    ;
   290:L P[290] 100mm/sec CNT0    ;
   291:L P[291] 100mm/sec CNT0    ;
   292:L P[292] 100mm/sec CNT0    ;
   293:L P[293] 100mm/sec CNT0    ;
   294:L P[294] 100mm/sec CNT0    ;
   295:L P[295] 100mm/sec CNT0    ;
   296:L P[296] 100mm/sec CNT0    ;
   297:L P[297] 100mm/sec CNT0    ;
   298:L P[298] 100mm/sec CNT0    ;
   299:L P[299] 100mm/sec CNT0    ;
   300:L P[300] 100mm/sec CNT0    ;
   301:L P[301] 100mm/sec CNT0    ;
   302:L P[302] 100mm/sec CNT0    ;
   303:L P[303] 100mm/sec CNT0    ;
   304:L P[304] 100mm/sec CNT0    ;
   305:L P[305] 100mm/sec CNT0    ;
   306:L P[306] 100mm/sec CNT0    ;
   307:L P[307] 100mm/sec CNT0    ;
   308:L P[308] 100mm/sec CNT0    ;
   309:L P[309] 100mm/sec CNT0    ;
   310:L P[310] 100mm/sec CNT0    ;
   311:L P[311] 100mm/sec CNT0    ;
   312:L P[312] 100mm/sec CNT0    ;
   313:L P[313] 100mm/sec CNT0    ;
   314:L P[314] 100mm/sec CNT0    ;
   315:L P[315] 100mm/sec CNT0    ;
   316:L P[316] 100mm/sec CNT0    ;
   317:L P[317] 100mm/sec CNT0    ;
   318:L P[318] 100mm/sec CNT0    ;
   319:L P[319] 100mm/sec CNT0    ;
   320:L P[320] 100mm/sec CNT0    ;
   321:L P[321] 100mm/sec CNT0    ;
   322:L P[322] 100mm/sec CNT0    ;
   323:L P[323] 100mm/sec CNT0    ;
   324:L P[324] 100mm/sec CNT0    ;
   325:L P[325] 100mm/sec CNT0    ;
   326:L P[326] 100mm/sec CNT0    ;
   327:L P[327] 100mm/sec CNT0    ;
   328:L P[328] 100mm/sec CNT0    ;
   329:L P[329] 100mm/sec CNT0    ;
   330:L P[330] 100mm/sec CNT0    ;
   331:L P[331] 100mm/sec CNT0    ;
   332:L P[332] 100mm/sec CNT0    ;
   333:L P[333] 100mm/sec CNT0    ;
   334:L P[334] 100mm/sec CNT0    ;
   335:L P[335] 100mm/sec CNT0    ;
   336:L P[336] 100mm/sec CNT0    ;
   337:L P[337] 100mm/sec CNT0    ;
   338:L P[338] 100mm/sec CNT0    ;
   339:L P[339] 100mm/sec CNT0    ;
   340:L P[340] 100mm/sec CNT0    ;
   341:L P[341] 100mm/sec CNT0    ;
   342:L P[342] 100mm/sec CNT0    ;
   343:L P[343] 100mm/sec CNT0    ;
   344:L P[344] 100mm/sec CNT0    ;
   345:L P[345] 100mm/sec CNT0    ;
   346:L P[346] 100mm/sec CNT0    ;
   347:L P[347] 100mm/sec CNT0    ;
   348:L P[348] 100mm/sec CNT0    ;
   349:L P[349] 100mm/sec CNT0    ;
   350:L P[350] 100mm/sec CNT0    ;
   351:L P[351] 100mm/sec CNT0    ;
   352:L P[352] 100mm/sec CNT0    ;
   353:L P[353] 100mm/sec CNT0    ;
   354:L P[354] 100mm/sec CNT0    ;
   355:L P[355] 100mm/sec CNT0    ;
   356:L P[356] 100mm/sec CNT0    ;
   357:L P[357] 100mm/sec CNT0    ;
   358:L P[358] 100mm/sec CNT0    ;
   359:L P[359] 100mm/sec CNT0    ;
   360:L P[360] 100mm/sec CNT0    ;
   361:L P[361] 100mm/sec CNT0    ;
   362:L P[362] 100mm/sec CNT0    ;
   363:L P[363] 100mm/sec CNT0    ;
   364:L P[364] 100mm/sec CNT0    ;
   365:L P[365] 100mm/sec CNT0    ;
   366:L P[366] 100mm/sec CNT0    ;
   367:L P[367] 100mm/sec CNT0    ;
   368:L P[368] 100mm/sec CNT0    ;
   369:L P[369] 100mm/sec CNT0    ;
   370:L P[370] 100mm/sec CNT0    ;
   371:L P[371] 100mm/sec CNT0    ;
   372:L P[372] 100mm/sec CNT0    ;
   373:L P[373] 100mm/sec CNT0    ;
   374:L P[374] 100mm/sec CNT0    ;
   375:L P[375] 100mm/sec CNT0    ;
   376:L P[376] 100mm/sec CNT0    ;
   377:L P[377] 100mm/sec CNT0    ;
   378:L P[378] 100mm/sec CNT0    ;
   379:L P[379] 100mm/sec CNT0    ;
   380:L P[380] 100mm/sec CNT0    ;
   381:L P[381] 100mm/sec CNT0    ;
   382:L P[382] 100mm/sec CNT0    ;
   383:L P[383] 100mm/sec CNT0    ;
   384:L P[384] 100mm/sec CNT0    ;
   385:L P[385] 100mm/sec CNT0    ;
   386:L P[386] 100mm/sec CNT0    ;
   387:L P[387] 100mm/sec CNT0    ;
   388:L P[388] 100mm/sec CNT0    ;
   389:L P[389] 100mm/sec CNT0    ;
   390:L P[390] 100mm/sec CNT0    ;
   391:L P[391] 100mm/sec CNT0    ;
   392:L P[392] 100mm/sec CNT0    ;
   393:L P[393] 100mm/sec CNT0    ;
   394:L P[394] 100mm/sec CNT0    ;
   395:L P[395] 100mm/sec CNT0    ;
   396:L P[396] 100mm/sec CNT0    ;
   397:L P[397] 100mm/sec CNT0    ;
   398:L P[398] 100mm/sec CNT0    ;
   399:L P[399] 100mm/sec CNT0    ;
   400:L P[400] 100mm/sec CNT0    ;
   401:L P[401] 100mm/sec CNT0    ;
   402:L P[402] 100mm/sec CNT0    ;
   403:L P[403] 100mm/sec CNT0    ;
   404:L P[404] 100mm/sec CNT0    ;
   405:L P[405] 100mm/sec CNT0    ;
   406:L P[406] 100mm/sec CNT0    ;
   407:L P[407] 100mm/sec CNT0    ;
   408:L P[408] 100mm/sec CNT0    ;
   409:L P[409] 100mm/sec CNT0    ;
   410:L P[410] 100mm/sec CNT0    ;
   411:L P[411] 100mm/sec CNT0    ;
   412:L P[412] 100mm/sec CNT0    ;
   413:L P[413] 100mm/sec CNT0    ;
   414:L P[414] 100mm/sec CNT0    ;
   415:L P[415] 100mm/sec CNT0    ;
   416:L P[416] 100mm/sec CNT0    ;
   417:L P[417] 100mm/sec CNT0    ;
   418:L P[418] 100mm/sec CNT0    ;
   419:L P[419] 100mm/sec CNT0    ;
   420:L P[420] 100mm/sec CNT0    ;
   421:L P[421] 100mm/sec CNT0    ;
   422:L P[422] 100mm/sec CNT0    ;
   423:L P[423] 100mm/sec CNT0    ;
   424:L P[424] 100mm/sec CNT0    ;
   425:L P[425] 100mm/sec CNT0    ;
   426:L P[426] 100mm/sec CNT0    ;
   427:L P[427] 100mm/sec CNT0    ;
   428:L P[428] 100mm/sec CNT0    ;
   429:L P[429] 100mm/sec CNT0    ;
   430:L P[430] 100mm/sec CNT0    ;
   431:L P[431] 100mm/sec CNT0    ;
   432:L P[432] 100mm/sec CNT0    ;
   433:L P[433] 100mm/sec CNT0    ;
   434:L P[434] 100mm/sec CNT0    ;
   435:L P[435] 100mm/sec CNT0    ;
   436:L P[436] 100mm/sec CNT0    ;
   437:L P[437] 100mm/sec CNT0    ;
   438:L P[438] 100mm/sec CNT0    ;
   439:L P[439] 100mm/sec CNT0    ;
   440:L P[440] 100mm/sec CNT0    ;
   441:L P[441] 100mm/sec CNT0    ;
   442:L P[442] 100mm/sec CNT0    ;
   443:L P[443] 100mm/sec CNT0    ;
   444:L P[444] 100mm/sec CNT0    ;
   445:L P[445] 100mm/sec CNT0    ;
   446:L P[446] 100mm/sec CNT0    ;
   447:L P[447] 100mm/sec CNT0    ;
   448:L P[448] 100mm/sec CNT0    ;
   449:L P[449] 100mm/sec CNT0    ;
   450:L P[450] 100mm/sec CNT0    ;
   451:L P[451] 100mm/sec CNT0    ;
   452:L P[452] 100mm/sec CNT0    ;
   453:L P[453] 100mm/sec CNT0    ;
   454:L P[454] 100mm/sec CNT0    ;
   455:L P[455] 100mm/sec CNT0    ;
   456:L P[456] 100mm/sec CNT0    ;
   457:L P[457] 100mm/sec CNT0    ;
   458:L P[458] 100mm/sec CNT0    ;
   459:L P[459] 100mm/sec CNT0    ;
   460:L P[460] 100mm/sec CNT0    ;
   461:L P[461] 100mm/sec CNT0    ;
   462:L P[462] 100mm/sec CNT0    ;
   463:L P[463] 100mm/sec CNT0    ;
   464:L P[464] 100mm/sec CNT0    ;
   465:L P[465] 100mm/sec CNT0    ;
   466:L P[466] 100mm/sec CNT0    ;
   467:L P[467] 100mm/sec CNT0    ;
   468:L P[468] 100mm/sec CNT0    ;
   469:L P[469] 100mm/sec CNT0    ;
   470:L P[470] 100mm/sec CNT0    ;
   471:L P[471] 100mm/sec CNT0    ;
   472:L P[472] 100mm/sec CNT0    ;
   473:L P[473] 100mm/sec CNT0    ;
   474:L P[474] 100mm/sec CNT0    ;
   475:L P[475] 100mm/sec CNT0    ;
   476:L P[476] 100mm/sec CNT0    ;
   477:L P[477] 100mm/sec CNT0    ;
   478:L P[478] 100mm/sec CNT0    ;
   479:L P[479] 100mm/sec CNT0    ;
   480:L P[480] 100mm/sec CNT0    ;
   481:L P[481] 100mm/sec CNT0    ;
   482:L P[482] 100mm/sec CNT0    ;
   483:L P[483] 100mm/sec CNT0    ;
   484:L P[484] 100mm/sec CNT0    ;
   485:L P[485] 100mm/sec CNT0    ;
   486:L P[486] 100mm/sec CNT0    ;
   487:L P[487] 100mm/sec CNT0    ;
   488:L P[488] 100mm/sec CNT0    ;
   489:L P[489] 100mm/sec CNT0    ;
   490:L P[490] 100mm/sec CNT0    ;
   491:L P[491] 100mm/sec CNT0    ;
   492:L P[492] 100mm/sec CNT0    ;
   493:L P[493] 100mm/sec CNT0    ;
   494:L P[494] 100mm/sec CNT0    ;
   495:L P[495] 100mm/sec CNT0    ;
   496:L P[496] 100mm/sec CNT0    ;
   497:L P[497] 100mm/sec CNT0    ;
   498:L P[498] 100mm/sec CNT0    ;
   499:L P[499] 100mm/sec CNT0    ;
   500:L P[500] 100mm/sec CNT0    ;
   501:L P[501] 100mm/sec CNT0    ;
   502:L P[502] 100mm/sec CNT0    ;
   503:L P[503] 100mm/sec CNT0    ;
   504:L P[504] 100mm/sec CNT0    ;
   505:L P[505] 100mm/sec CNT0    ;
   506:L P[506] 100mm/sec CNT0    ;
   507:L P[507] 100mm/sec CNT0    ;
   508:L P[508] 100mm/sec CNT0    ;
   509:L P[509] 100mm/sec CNT0    ;
   510:L P[510] 100mm/sec CNT0    ;
   511:L P[511] 100mm/sec CNT0    ;
   512:L P[512] 100mm/sec CNT0    ;
   513:L P[513] 100mm/sec CNT0    ;
   514:L P[514] 100mm/sec CNT0    ;
   515:L P[515] 100mm/sec CNT0    ;
   516:L P[516] 100mm/sec CNT0    ;
   517:L P[517] 100mm/sec CNT0    ;
   518:L P[518] 100mm/sec CNT0    ;
   519:L P[519] 100mm/sec CNT0    ;
   520:L P[520] 100mm/sec CNT0    ;
   521:L P[521] 100mm/sec CNT0    ;
   522:L P[522] 100mm/sec CNT0    ;
   523:L P[523] 100mm/sec CNT0    ;
   524:L P[524] 100mm/sec CNT0    ;
   525:L P[525] 100mm/sec CNT0    ;
   526:L P[526] 100mm/sec CNT0    ;
   527:L P[527] 100mm/sec CNT0    ;
   528:L P[528] 100mm/sec CNT0    ;
   529:L P[529] 100mm/sec CNT0    ;
   530:L P[530] 100mm/sec CNT0    ;
   531:L P[531] 100mm/sec CNT0    ;
   532:L P[532] 100mm/sec CNT0    ;
   533:L P[533] 100mm/sec CNT0    ;
   534:L P[534] 100mm/sec CNT0    ;
   535:L P[535] 100mm/sec CNT0    ;
   536:L P[536] 100mm/sec CNT0    ;
   537:L P[537] 100mm/sec CNT0    ;
   538:L P[538] 100mm/sec CNT0    ;
   539:L P[539] 100mm/sec CNT0    ;
   540:L P[540] 100mm/sec CNT0    ;
   541:L P[541] 100mm/sec CNT0    ;
   542:L P[542] 100mm/sec CNT0    ;
   543:L P[543] 100mm/sec CNT0    ;
   544:L P[544] 100mm/sec CNT0    ;
   545:L P[545] 100mm/sec CNT0    ;
   546:L P[546] 100mm/sec CNT0    ;
   547:L P[547] 100mm/sec CNT0    ;
   548:L P[548] 100mm/sec CNT0    ;
   549:L P[549] 100mm/sec CNT0    ;
   550:L P[550] 100mm/sec CNT0    ;
   551:L P[551] 100mm/sec CNT0    ;
   552:L P[552] 100mm/sec CNT0    ;
   553:L P[553] 100mm/sec CNT0    ;
   554:L P[554] 100mm/sec CNT0    ;
   555:L P[555] 100mm/sec CNT0    ;
   556:L P[556] 100mm/sec CNT0    ;
   557:L P[557] 100mm/sec CNT0    ;
   558:L P[558] 100mm/sec CNT0    ;
   559:L P[559] 100mm/sec CNT0    ;
   560:L P[560] 100mm/sec CNT0    ;
   561:L P[561] 100mm/sec CNT0    ;
   562:L P[562] 100mm/sec CNT0    ;
   563:L P[563] 100mm/sec CNT0    ;
   564:L P[564] 100mm/sec CNT0    ;
   565:L P[565] 100mm/sec CNT0    ;
   566:L P[566] 100mm/sec CNT0    ;
   567:L P[567] 100mm/sec CNT0    ;
   568:L P[568] 100mm/sec CNT0    ;
   569:L P[569] 100mm/sec CNT0    ;
   570:L P[570] 100mm/sec CNT0    ;
   571:L P[571] 100mm/sec CNT0    ;
   572:L P[572] 100mm/sec CNT0    ;
   573:L P[573] 100mm/sec CNT0    ;
   574:L P[574] 100mm/sec CNT0    ;
   575:L P[575] 100mm/sec CNT0    ;
   576:L P[576] 100mm/sec CNT0    ;
   577:L P[577] 100mm/sec CNT0    ;
   578:L P[578] 100mm/sec CNT0    ;
   579:L P[579] 100mm/sec CNT0    ;
   580:L P[580] 100mm/sec CNT0    ;
   581:L P[581] 100mm/sec CNT0    ;
   582:L P[582] 100mm/sec CNT0    ;
   583:L P[583] 100mm/sec CNT0    ;
   584:L P[584] 100mm/sec CNT0    ;
   585:L P[585] 100mm/sec CNT0    ;
   586:L P[586] 100mm/sec CNT0    ;
   587:L P[587] 100mm/sec CNT0    ;
   588:L P[588] 100mm/sec CNT0    ;
   589:L P[589] 100mm/sec CNT0    ;
   590:L P[590] 100mm/sec CNT0    ;
   591:L P[591] 100mm/sec CNT0    ;
   592:L P[592] 100mm/sec CNT0    ;
   593:L P[593] 100mm/sec CNT0    ;
   594:L P[594] 100mm/sec CNT0    ;
   595:L P[595] 100mm/sec CNT0    ;
   596:L P[596] 100mm/sec CNT0    ;
   597:L P[597] 100mm/sec CNT0    ;
   598:L P[598] 100mm/sec CNT0    ;
   599:L P[599] 100mm/sec CNT0    ;
   600:L P[600] 100mm/sec CNT0    ;
   601:L P[601] 100mm/sec CNT0    ;
   602:L P[602] 100mm/sec CNT0    ;
   603:L P[603] 100mm/sec CNT0    ;
   604:L P[604] 100mm/sec CNT0    ;
   605:L P[605] 100mm/sec CNT0    ;
   606:L P[606] 100mm/sec CNT0    ;
   607:L P[607] 100mm/sec CNT0    ;
   608:L P[608] 100mm/sec CNT0    ;
   609:L P[609] 100mm/sec CNT0    ;
   610:L P[610] 100mm/sec CNT0    ;
   611:L P[611] 100mm/sec CNT0    ;
   612:L P[612] 100mm/sec CNT0    ;
   613:L P[613] 100mm/sec CNT0    ;
   614:L P[614] 100mm/sec CNT0    ;
   615:L P[615] 100mm/sec CNT0    ;
   616:L P[616] 100mm/sec CNT0    ;
   617:L P[617] 100mm/sec CNT0    ;
   618:L P[618] 100mm/sec CNT0    ;
   619:L P[619] 100mm/sec CNT0    ;
   620:L P[620] 100mm/sec CNT0    ;
   621:L P[621] 100mm/sec CNT0    ;
   622:L P[622] 100mm/sec CNT0    ;
   623:L P[623] 100mm/sec CNT0    ;
   624:L P[624] 100mm/sec CNT0    ;
   625:L P[625] 100mm/sec CNT0    ;
   626:L P[626] 100mm/sec CNT0    ;
   627:L P[627] 100mm/sec CNT0    ;
   628:L P[628] 100mm/sec CNT0    ;
   629:L P[629] 100mm/sec CNT0    ;
   630:L P[630] 100mm/sec CNT0    ;
   631:L P[631] 100mm/sec CNT0    ;
   632:L P[632] 100mm/sec CNT0    ;
   633:L P[633] 100mm/sec CNT0    ;
   634:L P[634] 100mm/sec CNT0    ;
   635:L P[635] 100mm/sec CNT0    ;
   636:L P[636] 100mm/sec CNT0    ;
   637:L P[637] 100mm/sec CNT0    ;
   638:L P[638] 100mm/sec CNT0    ;
   639:L P[639] 100mm/sec CNT0    ;
   640:L P[640] 100mm/sec CNT0    ;
   641:L P[641] 100mm/sec CNT0    ;
   642:L P[642] 100mm/sec CNT0    ;
   643:L P[643] 100mm/sec CNT0    ;
/POS
P[1]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -31.809  mm,	Y =   -361.132  mm,	Z =   -248.257  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[2]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -13.574  mm,	Y =   -350.591  mm,	Z =   -248.228  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[3]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  4.677  mm,	Y =   -339.997  mm,	Z =   -248.092  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[4]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  22.892  mm,	Y =   -329.513  mm,	Z =   -248.173  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[5]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  41.038  mm,	Y =   -318.987  mm,	Z =   -248.053  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[6]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  59.238  mm,	Y =   -308.568  mm,	Z =   -248.271  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[7]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  77.275  mm,	Y =   -298.079  mm,	Z =   -248.091  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[8]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  95.689  mm,	Y =   -287.499  mm,	Z =   -248.218  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[9]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  113.945  mm,	Y =   -276.982  mm,	Z =   -248.275  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[10]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  132.143  mm,	Y =   -266.481  mm,	Z =   -248.291  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[11]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  150.251  mm,	Y =   -255.991  mm,	Z =   -248.206  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[12]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  168.212  mm,	Y =   -245.671  mm,	Z =   -248.329  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[13]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.398  mm,	Y =   -235.131  mm,	Z =   -248.231  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[14]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.720  mm,	Y =   -224.506  mm,	Z =   -248.119  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[15]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.840  mm,	Y =   -214.109  mm,	Z =   -248.279  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[16]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.080  mm,	Y =   -203.415  mm,	Z =   -247.885  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[17]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.295  mm,	Y =   -192.996  mm,	Z =   -248.124  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[18]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  277.476  mm,	Y =   -182.563  mm,	Z =   -248.281  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[19]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  295.634  mm,	Y =   -172.023  mm,	Z =   -248.145  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[20]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  313.885  mm,	Y =   -161.527  mm,	Z =   -248.246  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[21]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  331.990  mm,	Y =   -151.053  mm,	Z =   -248.197  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[22]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  349.935  mm,	Y =   -140.732  mm,	Z =   -248.296  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[23]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  368.304  mm,	Y =   -130.083  mm,	Z =   -248.191  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[24]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  386.701  mm,	Y =   -119.475  mm,	Z =   -248.226  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[25]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  404.691  mm,	Y =   -109.045  mm,	Z =   -248.122  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[26]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  423.535  mm,	Y =   -99.008  mm,	Z =   -248.380  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[27]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -49.901  mm,	Y =   -371.870  mm,	Z =   -248.349  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[28]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -60.791  mm,	Y =   -381.847  mm,	Z =   -245.917  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[29]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  436.516  mm,	Y =   -95.591  mm,	Z =   -244.664  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[30]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  407.027  mm,	Y =   -113.469  mm,	Z =   -262.006  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[31]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  388.967  mm,	Y =   -123.904  mm,	Z =   -262.006  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[32]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  370.491  mm,	Y =   -134.487  mm,	Z =   -261.823  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[33]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  352.499  mm,	Y =   -144.864  mm,	Z =   -261.816  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[34]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  334.542  mm,	Y =   -155.326  mm,	Z =   -262.017  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[35]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  316.355  mm,	Y =   -165.838  mm,	Z =   -262.028  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[36]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  298.223  mm,	Y =   -176.211  mm,	Z =   -261.822  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[37]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  279.684  mm,	Y =   -186.979  mm,	Z =   -261.963  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[38]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.689  mm,	Y =   -197.300  mm,	Z =   -261.819  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[39]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.529  mm,	Y =   -207.877  mm,	Z =   -262.030  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[40]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.327  mm,	Y =   -218.283  mm,	Z =   -261.789  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[41]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  207.095  mm,	Y =   -228.956  mm,	Z =   -262.079  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[42]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.087  mm,	Y =   -239.301  mm,	Z =   -261.985  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[43]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  170.773  mm,	Y =   -249.755  mm,	Z =   -261.734  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[44]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  152.722  mm,	Y =   -260.327  mm,	Z =   -262.037  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[45]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  134.441  mm,	Y =   -270.856  mm,	Z =   -261.997  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[46]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  116.386  mm,	Y =   -281.258  mm,	Z =   -261.946  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[47]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  97.967  mm,	Y =   -291.851  mm,	Z =   -261.848  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[48]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  79.798  mm,	Y =   -302.381  mm,	Z =   -261.928  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[49]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  61.913  mm,	Y =   -312.808  mm,	Z =   -262.131  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[50]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  43.606  mm,	Y =   -323.304  mm,	Z =   -261.992  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[51]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  25.404  mm,	Y =   -333.812  mm,	Z =   -261.973  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[52]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  7.212  mm,	Y =   -344.314  mm,	Z =   -261.960  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[53]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -11.227  mm,	Y =   -354.953  mm,	Z =   -261.983  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[54]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -29.329  mm,	Y =   -365.393  mm,	Z =   -261.944  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[55]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -45.990  mm,	Y =   -375.318  mm,	Z =   -261.551  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[56]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  423.447  mm,	Y =   -104.475  mm,	Z =   -261.474  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[57]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -55.297  mm,	Y =   -383.367  mm,	Z =   -257.856  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[58]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  435.567  mm,	Y =   -100.784  mm,	Z =   -255.373  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[59]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  444.752  mm,	Y =   -106.624  mm,	Z =   -248.252  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[60]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  433.128  mm,	Y =   -112.889  mm,	Z =   -265.651  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[61]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  413.824  mm,	Y =   -124.649  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[62]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  377.414  mm,	Y =   -145.540  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[63]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  359.211  mm,	Y =   -156.155  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[64]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  341.045  mm,	Y =   -166.682  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[65]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  322.723  mm,	Y =   -177.198  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[66]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  304.469  mm,	Y =   -187.717  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[67]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.050  mm,	Y =   -219.225  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[68]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.728  mm,	Y =   -229.498  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[69]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  213.933  mm,	Y =   -240.008  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[70]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  158.988  mm,	Y =   -271.676  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[71]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  140.962  mm,	Y =   -282.056  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[72]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  122.572  mm,	Y =   -292.720  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[73]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  104.562  mm,	Y =   -303.179  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[74]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  86.299  mm,	Y =   -313.689  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[75]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  50.066  mm,	Y =   -334.597  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[76]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  31.809  mm,	Y =   -345.188  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[77]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -4.736  mm,	Y =   -366.229  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[78]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -41.738  mm,	Y =   -387.082  mm,	Z =   -266.659  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[79]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -56.395  mm,	Y =   -396.149  mm,	Z =   -248.155  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[80]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -22.662  mm,	Y =   -376.780  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[81]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  13.579  mm,	Y =   -355.966  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[82]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  68.286  mm,	Y =   -324.429  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[83]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  177.360  mm,	Y =   -261.258  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[84]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  195.556  mm,	Y =   -250.748  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[85]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  268.163  mm,	Y =   -208.831  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[86]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.500  mm,	Y =   -198.303  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[87]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  395.861  mm,	Y =   -135.084  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[88]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -51.443  mm,	Y =   -394.780  mm,	Z =   -261.350  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[89]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  443.086  mm,	Y =   -111.032  mm,	Z =   -258.743  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[90]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  455.491  mm,	Y =   -124.799  mm,	Z =   -248.223  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[91]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  452.105  mm,	Y =   -126.497  mm,	Z =   -258.821  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[92]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  443.722  mm,	Y =   -131.560  mm,	Z =   -266.228  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[93]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  333.247  mm,	Y =   -195.386  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[94]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  315.256  mm,	Y =   -205.828  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[95]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  296.757  mm,	Y =   -216.429  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[96]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.636  mm,	Y =   -237.340  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[97]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.817  mm,	Y =   -258.548  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[98]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  169.615  mm,	Y =   -289.788  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[99]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  133.153  mm,	Y =   -310.843  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[100]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  115.122  mm,	Y =   -321.384  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[101]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  96.869  mm,	Y =   -331.935  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[102]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  42.223  mm,	Y =   -363.503  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[103]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  24.029  mm,	Y =   -373.863  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[104]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  5.890  mm,	Y =   -384.356  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[105]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -30.404  mm,	Y =   -405.401  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[106]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -41.809  mm,	Y =   -411.814  mm,	Z =   -262.036  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[107]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -46.152  mm,	Y =   -414.324  mm,	Z =   -248.145  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[108]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -12.296  mm,	Y =   -395.083  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[109]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  60.398  mm,	Y =   -353.015  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[110]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  78.654  mm,	Y =   -342.480  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[111]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  151.581  mm,	Y =   -300.455  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[112]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.782  mm,	Y =   -279.471  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[113]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  206.005  mm,	Y =   -269.239  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[114]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.553  mm,	Y =   -247.961  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[115]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  278.869  mm,	Y =   -226.934  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[116]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  351.630  mm,	Y =   -184.922  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[117]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  369.695  mm,	Y =   -174.445  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[118]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  387.893  mm,	Y =   -163.995  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[119]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  406.104  mm,	Y =   -153.664  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[120]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  424.288  mm,	Y =   -142.905  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[121]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  466.055  mm,	Y =   -143.025  mm,	Z =   -248.125  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[122]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  462.572  mm,	Y =   -144.597  mm,	Z =   -258.781  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[123]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  434.832  mm,	Y =   -160.957  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[124]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  398.312  mm,	Y =   -182.100  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[125]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  380.227  mm,	Y =   -192.548  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[126]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  362.231  mm,	Y =   -202.867  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[127]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.078  mm,	Y =   -245.026  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[128]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  271.201  mm,	Y =   -255.519  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[129]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  216.386  mm,	Y =   -287.017  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[130]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  161.866  mm,	Y =   -318.604  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[131]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  143.727  mm,	Y =   -329.140  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[132]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  88.971  mm,	Y =   -360.336  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[133]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  71.002  mm,	Y =   -371.020  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[134]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  34.510  mm,	Y =   -392.123  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[135]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -1.726  mm,	Y =   -413.086  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[136]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -20.049  mm,	Y =   -423.440  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[137]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -31.278  mm,	Y =   -430.090  mm,	Z =   -262.026  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[138]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -35.591  mm,	Y =   -432.560  mm,	Z =   -248.221  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[139]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  16.490  mm,	Y =   -402.778  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[140]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  52.966  mm,	Y =   -381.569  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[141]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  107.404  mm,	Y =   -350.135  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[142]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  125.597  mm,	Y =   -339.631  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[143]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  180.340  mm,	Y =   -308.161  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[144]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  198.465  mm,	Y =   -297.651  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[145]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.762  mm,	Y =   -276.716  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[146]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.969  mm,	Y =   -266.092  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[147]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  307.612  mm,	Y =   -234.727  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[148]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  325.538  mm,	Y =   -224.201  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[149]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  343.772  mm,	Y =   -213.717  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[150]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  416.839  mm,	Y =   -171.494  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[151]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  454.424  mm,	Y =   -149.917  mm,	Z =   -266.201  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[152]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  473.172  mm,	Y =   -162.980  mm,	Z =   -258.817  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[153]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  464.797  mm,	Y =   -167.912  mm,	Z =   -266.226  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[154]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  426.892  mm,	Y =   -189.817  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[155]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  408.688  mm,	Y =   -200.247  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[156]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  354.175  mm,	Y =   -231.847  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[157]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  336.349  mm,	Y =   -242.063  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[158]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  317.826  mm,	Y =   -252.429  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[159]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  299.754  mm,	Y =   -263.236  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[160]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  263.759  mm,	Y =   -284.076  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[161]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.237  mm,	Y =   -294.759  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[162]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.083  mm,	Y =   -305.102  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[163]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  136.063  mm,	Y =   -357.743  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[164]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  27.224  mm,	Y =   -420.619  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[165]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -9.446  mm,	Y =   -441.815  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[166]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -20.850  mm,	Y =   -448.322  mm,	Z =   -261.783  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[167]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -24.883  mm,	Y =   -451.092  mm,	Z =   -248.240  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[168]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  8.761  mm,	Y =   -431.371  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[169]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  45.385  mm,	Y =   -410.246  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[170]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  63.492  mm,	Y =   -399.909  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[171]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  81.644  mm,	Y =   -389.262  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[172]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  99.796  mm,	Y =   -378.805  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[173]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  118.105  mm,	Y =   -368.396  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[174]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  154.231  mm,	Y =   -347.358  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[175]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  172.550  mm,	Y =   -337.050  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[176]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.804  mm,	Y =   -326.261  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[177]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  208.972  mm,	Y =   -315.792  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[178]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.514  mm,	Y =   -273.907  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[179]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  372.666  mm,	Y =   -221.346  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[180]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  390.961  mm,	Y =   -210.787  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[181]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  445.239  mm,	Y =   -179.306  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[182]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  476.533  mm,	Y =   -161.268  mm,	Z =   -248.260  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[183]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  487.063  mm,	Y =   -179.401  mm,	Z =   -248.112  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[184]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  483.627  mm,	Y =   -180.993  mm,	Z =   -258.685  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[185]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  475.326  mm,	Y =   -186.073  mm,	Z =   -266.214  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[186]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  401.184  mm,	Y =   -228.947  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[187]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.957  mm,	Y =   -291.804  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[188]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  273.871  mm,	Y =   -302.477  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[189]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  164.789  mm,	Y =   -365.394  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[190]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  146.570  mm,	Y =   -375.798  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[191]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  128.265  mm,	Y =   -386.276  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[192]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  37.286  mm,	Y =   -439.018  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[193]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  19.038  mm,	Y =   -449.399  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[194]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  1.025  mm,	Y =   -459.781  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[195]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -14.524  mm,	Y =   -469.116  mm,	Z =   -248.124  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[196]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -10.199  mm,	Y =   -466.600  mm,	Z =   -262.022  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[197]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  55.625  mm,	Y =   -428.607  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[198]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  73.843  mm,	Y =   -418.122  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[199]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  91.889  mm,	Y =   -407.635  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[200]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  110.310  mm,	Y =   -397.001  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[201]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  183.017  mm,	Y =   -355.077  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[202]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.119  mm,	Y =   -344.612  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[203]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.292  mm,	Y =   -334.125  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[204]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.593  mm,	Y =   -323.508  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[205]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  255.772  mm,	Y =   -312.969  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[206]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  310.429  mm,	Y =   -281.547  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[207]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  328.350  mm,	Y =   -271.192  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[208]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  346.593  mm,	Y =   -260.564  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[209]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  364.920  mm,	Y =   -250.189  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[210]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  382.970  mm,	Y =   -239.520  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[211]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  419.478  mm,	Y =   -218.511  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[212]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  437.579  mm,	Y =   -208.077  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[213]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  455.798  mm,	Y =   -197.474  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[214]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  494.215  mm,	Y =   -199.444  mm,	Z =   -258.845  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[215]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  485.628  mm,	Y =   -204.406  mm,	Z =   -266.289  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[216]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  466.222  mm,	Y =   -215.528  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[217]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  448.070  mm,	Y =   -225.888  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[218]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  430.013  mm,	Y =   -236.544  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[219]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  411.628  mm,	Y =   -246.887  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[220]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  393.435  mm,	Y =   -257.510  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[221]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  375.194  mm,	Y =   -268.133  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[222]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  357.066  mm,	Y =   -278.630  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[223]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  320.539  mm,	Y =   -299.491  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[224]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  302.582  mm,	Y =   -310.151  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[225]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.863  mm,	Y =   -351.989  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[226]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  193.528  mm,	Y =   -372.991  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[227]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  175.320  mm,	Y =   -383.626  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[228]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  156.918  mm,	Y =   -393.998  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[229]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  138.803  mm,	Y =   -404.660  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[230]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  120.591  mm,	Y =   -414.995  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[231]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  102.460  mm,	Y =   -425.595  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[232]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  84.320  mm,	Y =   -435.984  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[233]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  47.774  mm,	Y =   -457.188  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[234]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  0.192  mm,	Y =   -484.715  mm,	Z =   -261.841  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[235]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  -4.024  mm,	Y =   -487.316  mm,	Z =   -248.104  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[236]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  11.682  mm,	Y =   -478.284  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[237]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  29.795  mm,	Y =   -467.734  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[238]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  66.237  mm,	Y =   -447.013  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[239]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  211.840  mm,	Y =   -362.642  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[240]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.162  mm,	Y =   -341.722  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[241]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  266.333  mm,	Y =   -331.224  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[242]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  284.315  mm,	Y =   -320.770  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[243]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  339.039  mm,	Y =   -289.179  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[244]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  497.526  mm,	Y =   -197.659  mm,	Z =   -248.306  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[245]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  496.058  mm,	Y =   -222.588  mm,	Z =   -266.270  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[246]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  476.898  mm,	Y =   -233.749  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[247]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  440.358  mm,	Y =   -254.870  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[248]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  422.178  mm,	Y =   -265.289  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[249]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  385.792  mm,	Y =   -286.318  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[250]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  367.436  mm,	Y =   -296.810  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[251]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  349.238  mm,	Y =   -307.226  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[252]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  331.065  mm,	Y =   -317.515  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[253]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  276.639  mm,	Y =   -349.280  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[254]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.468  mm,	Y =   -359.885  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[255]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.319  mm,	Y =   -370.139  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[256]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  185.616  mm,	Y =   -401.880  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[257]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  149.258  mm,	Y =   -422.758  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[258]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  112.956  mm,	Y =   -443.690  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[259]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  94.960  mm,	Y =   -454.104  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[260]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  58.295  mm,	Y =   -475.413  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[261]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  22.091  mm,	Y =   -496.352  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[262]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  10.707  mm,	Y =   -502.846  mm,	Z =   -261.947  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[263]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  6.476  mm,	Y =   -505.480  mm,	Z =   -248.132  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[264]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  40.477  mm,	Y =   -485.848  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[265]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  76.867  mm,	Y =   -465.002  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[266]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  131.352  mm,	Y =   -433.333  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[267]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  167.611  mm,	Y =   -412.438  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[268]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.041  mm,	Y =   -391.475  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[269]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.035  mm,	Y =   -380.930  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[270]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  294.950  mm,	Y =   -338.848  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[271]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  313.242  mm,	Y =   -328.379  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[272]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  404.040  mm,	Y =   -275.859  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[273]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  458.934  mm,	Y =   -244.366  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[274]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  504.859  mm,	Y =   -217.760  mm,	Z =   -258.677  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[275]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  508.052  mm,	Y =   -215.797  mm,	Z =   -248.176  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[276]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  506.705  mm,	Y =   -240.811  mm,	Z =   -266.309  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[277]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  469.144  mm,	Y =   -262.492  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[278]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  450.730  mm,	Y =   -272.896  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[279]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  432.607  mm,	Y =   -283.438  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[280]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  359.942  mm,	Y =   -325.242  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[281]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  323.399  mm,	Y =   -346.502  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[282]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  305.415  mm,	Y =   -356.899  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[283]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  268.897  mm,	Y =   -377.947  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[284]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.615  mm,	Y =   -398.934  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[285]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  214.337  mm,	Y =   -409.538  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[286]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.214  mm,	Y =   -420.063  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[287]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  178.225  mm,	Y =   -430.430  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[288]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  160.028  mm,	Y =   -440.976  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[289]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  123.472  mm,	Y =   -462.024  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[290]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  105.313  mm,	Y =   -472.319  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[291]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  87.071  mm,	Y =   -482.946  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[292]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  50.805  mm,	Y =   -503.962  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[293]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  16.837  mm,	Y =   -523.410  mm,	Z =   -248.154  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[294]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  21.315  mm,	Y =   -521.162  mm,	Z =   -262.039  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[295]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  32.577  mm,	Y =   -514.814  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[296]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  68.897  mm,	Y =   -493.717  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[297]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  141.824  mm,	Y =   -451.538  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[298]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.752  mm,	Y =   -388.611  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[299]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.111  mm,	Y =   -367.710  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[300]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  341.811  mm,	Y =   -336.031  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[301]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  378.304  mm,	Y =   -314.965  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[302]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  396.407  mm,	Y =   -304.735  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[303]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  414.539  mm,	Y =   -294.037  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[304]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  487.247  mm,	Y =   -252.067  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[305]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  515.241  mm,	Y =   -235.918  mm,	Z =   -258.927  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[306]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  518.563  mm,	Y =   -234.048  mm,	Z =   -248.242  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[307]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  529.021  mm,	Y =   -252.114  mm,	Z =   -248.177  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[308]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  517.309  mm,	Y =   -258.916  mm,	Z =   -266.243  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[309]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  479.499  mm,	Y =   -280.543  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[310]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  443.083  mm,	Y =   -301.651  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[311]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  425.126  mm,	Y =   -311.951  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[312]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  406.641  mm,	Y =   -322.662  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[313]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  388.738  mm,	Y =   -333.116  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[314]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  370.499  mm,	Y =   -343.671  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[315]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  315.887  mm,	Y =   -375.174  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[316]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  297.549  mm,	Y =   -385.800  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[317]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  279.415  mm,	Y =   -396.191  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[318]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  206.612  mm,	Y =   -438.153  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[319]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.471  mm,	Y =   -448.692  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[320]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  170.478  mm,	Y =   -459.155  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[321]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  61.115  mm,	Y =   -522.203  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[322]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  43.115  mm,	Y =   -532.634  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[323]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  27.380  mm,	Y =   -541.695  mm,	Z =   -248.117  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[324]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  31.796  mm,	Y =   -539.369  mm,	Z =   -261.957  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[325]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  79.551  mm,	Y =   -511.789  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[326]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  97.701  mm,	Y =   -501.378  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[327]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  115.819  mm,	Y =   -490.828  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[328]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  133.975  mm,	Y =   -480.353  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[329]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  152.478  mm,	Y =   -469.659  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[330]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.048  mm,	Y =   -427.802  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[331]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.271  mm,	Y =   -417.399  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[332]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.432  mm,	Y =   -406.918  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[333]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  334.156  mm,	Y =   -364.931  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[334]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  352.385  mm,	Y =   -354.302  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[335]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  461.526  mm,	Y =   -291.229  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[336]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  497.856  mm,	Y =   -270.375  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[337]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  525.810  mm,	Y =   -254.171  mm,	Z =   -258.852  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[338]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  539.510  mm,	Y =   -270.346  mm,	Z =   -248.269  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[339]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  536.119  mm,	Y =   -271.982  mm,	Z =   -258.792  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[340]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  508.287  mm,	Y =   -288.249  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[341]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  471.880  mm,	Y =   -309.280  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[342]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  453.652  mm,	Y =   -319.779  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[343]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  417.249  mm,	Y =   -340.841  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[344]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  380.672  mm,	Y =   -361.947  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[345]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  362.759  mm,	Y =   -372.238  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[346]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  344.481  mm,	Y =   -382.813  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[347]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  271.675  mm,	Y =   -424.912  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[348]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.504  mm,	Y =   -445.815  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[349]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.108  mm,	Y =   -456.304  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[350]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  162.562  mm,	Y =   -487.707  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[351]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  107.982  mm,	Y =   -519.311  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[352]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  89.741  mm,	Y =   -529.781  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[353]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  53.581  mm,	Y =   -550.872  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[354]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  37.924  mm,	Y =   -559.909  mm,	Z =   -248.184  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[355]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  42.277  mm,	Y =   -557.568  mm,	Z =   -261.897  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[356]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  71.812  mm,	Y =   -540.629  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[357]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  126.552  mm,	Y =   -509.052  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[358]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  144.683  mm,	Y =   -498.469  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[359]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  180.969  mm,	Y =   -477.452  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[360]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.298  mm,	Y =   -466.868  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[361]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.741  mm,	Y =   -435.409  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[362]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.101  mm,	Y =   -414.633  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[363]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  308.097  mm,	Y =   -404.066  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[364]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  326.361  mm,	Y =   -393.441  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[365]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  399.287  mm,	Y =   -351.453  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[366]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  435.576  mm,	Y =   -330.414  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[367]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  490.205  mm,	Y =   -298.885  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[368]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  527.938  mm,	Y =   -277.059  mm,	Z =   -266.227  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[369]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  546.698  mm,	Y =   -290.274  mm,	Z =   -258.750  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[370]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  538.389  mm,	Y =   -295.148  mm,	Z =   -266.231  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[371]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  518.738  mm,	Y =   -306.286  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[372]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  463.970  mm,	Y =   -338.201  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[373]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  445.906  mm,	Y =   -348.392  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[374]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  427.877  mm,	Y =   -358.986  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[375]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  355.001  mm,	Y =   -401.120  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[376]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  336.851  mm,	Y =   -411.420  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[377]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  318.416  mm,	Y =   -421.995  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[378]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  300.626  mm,	Y =   -432.436  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[379]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.374  mm,	Y =   -453.459  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[380]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.939  mm,	Y =   -464.094  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[381]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  154.995  mm,	Y =   -516.551  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[382]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  118.642  mm,	Y =   -537.433  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[383]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  100.426  mm,	Y =   -548.129  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[384]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  48.394  mm,	Y =   -578.070  mm,	Z =   -248.144  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[385]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  52.818  mm,	Y =   -575.656  mm,	Z =   -262.084  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[386]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  64.435  mm,	Y =   -569.022  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[387]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  82.158  mm,	Y =   -558.753  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[388]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  137.145  mm,	Y =   -527.029  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[389]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  173.137  mm,	Y =   -506.235  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[390]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  191.462  mm,	Y =   -495.684  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[391]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  209.610  mm,	Y =   -485.105  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[392]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.864  mm,	Y =   -474.657  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[393]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.387  mm,	Y =   -443.207  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[394]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  373.303  mm,	Y =   -390.726  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[395]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  391.557  mm,	Y =   -380.055  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[396]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  409.543  mm,	Y =   -369.948  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[397]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  482.586  mm,	Y =   -327.497  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[398]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  500.569  mm,	Y =   -317.149  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[399]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  550.061  mm,	Y =   -288.560  mm,	Z =   -248.185  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[400]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  560.451  mm,	Y =   -306.631  mm,	Z =   -248.293  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[401]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  511.102  mm,	Y =   -335.246  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[402]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  492.857  mm,	Y =   -345.766  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[403]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  420.292  mm,	Y =   -387.497  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[404]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  365.367  mm,	Y =   -419.252  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[405]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  347.352  mm,	Y =   -429.738  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[406]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  329.172  mm,	Y =   -440.195  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[407]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.105  mm,	Y =   -492.724  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[408]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.900  mm,	Y =   -503.282  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[409]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  183.845  mm,	Y =   -524.142  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[410]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  63.149  mm,	Y =   -593.664  mm,	Z =   -261.964  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[411]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  58.862  mm,	Y =   -596.202  mm,	Z =   -248.142  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[412]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  74.501  mm,	Y =   -587.443  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[413]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  92.918  mm,	Y =   -576.851  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[414]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  110.957  mm,	Y =   -566.472  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[415]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  129.156  mm,	Y =   -555.925  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[416]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  147.305  mm,	Y =   -545.380  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[417]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  165.616  mm,	Y =   -534.799  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[418]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.980  mm,	Y =   -513.871  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[419]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.407  mm,	Y =   -482.361  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[420]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  274.730  mm,	Y =   -471.984  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[421]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.862  mm,	Y =   -461.336  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[422]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  311.046  mm,	Y =   -450.827  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[423]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  383.803  mm,	Y =   -409.042  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[424]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  401.879  mm,	Y =   -398.347  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[425]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  438.408  mm,	Y =   -377.314  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[426]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  456.547  mm,	Y =   -366.843  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[427]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  474.686  mm,	Y =   -356.459  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[428]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  529.359  mm,	Y =   -324.980  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[429]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  548.785  mm,	Y =   -313.535  mm,	Z =   -266.216  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[430]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  557.294  mm,	Y =   -308.702  mm,	Z =   -258.859  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[431]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  570.814  mm,	Y =   -324.514  mm,	Z =   -248.200  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[432]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  567.703  mm,	Y =   -326.733  mm,	Z =   -258.863  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[433]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  559.215  mm,	Y =   -331.737  mm,	Z =   -266.298  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[434]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  539.840  mm,	Y =   -342.732  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[435]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  503.278  mm,	Y =   -363.873  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[436]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  467.010  mm,	Y =   -384.898  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[437]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  430.638  mm,	Y =   -405.912  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[438]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  321.485  mm,	Y =   -468.955  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[439]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  303.278  mm,	Y =   -479.431  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[440]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.887  mm,	Y =   -510.794  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[441]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.541  mm,	Y =   -521.505  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[442]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.065  mm,	Y =   -542.556  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[443]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  139.530  mm,	Y =   -573.935  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[444]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  121.558  mm,	Y =   -584.313  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[445]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  69.455  mm,	Y =   -614.511  mm,	Z =   -248.193  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[446]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  73.807  mm,	Y =   -612.144  mm,	Z =   -261.927  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[447]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  85.175  mm,	Y =   -605.574  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[448]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  103.342  mm,	Y =   -595.091  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[449]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  158.046  mm,	Y =   -563.598  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[450]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  176.088  mm,	Y =   -553.101  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[451]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  212.495  mm,	Y =   -531.950  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[452]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  266.860  mm,	Y =   -500.614  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[453]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.368  mm,	Y =   -490.006  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[454]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  339.837  mm,	Y =   -458.448  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[455]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  357.990  mm,	Y =   -448.207  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[456]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  376.120  mm,	Y =   -437.531  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[457]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  394.238  mm,	Y =   -427.152  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[458]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  412.785  mm,	Y =   -416.547  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[459]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  448.959  mm,	Y =   -395.706  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[460]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  485.175  mm,	Y =   -374.654  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[461]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  521.461  mm,	Y =   -353.543  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[462]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  581.548  mm,	Y =   -343.057  mm,	Z =   -248.136  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[463]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  569.674  mm,	Y =   -349.887  mm,	Z =   -266.231  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[464]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  495.732  mm,	Y =   -392.513  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[465]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  477.461  mm,	Y =   -403.017  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[466]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  441.221  mm,	Y =   -424.060  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[467]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  404.597  mm,	Y =   -445.232  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[468]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  386.626  mm,	Y =   -455.612  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[469]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  368.349  mm,	Y =   -466.118  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[470]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  350.098  mm,	Y =   -476.669  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[471]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  313.809  mm,	Y =   -497.611  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[472]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.253  mm,	Y =   -529.033  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[473]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.975  mm,	Y =   -539.441  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[474]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.337  mm,	Y =   -571.044  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[475]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  131.747  mm,	Y =   -602.648  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[476]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  113.540  mm,	Y =   -613.030  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[477]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  79.956  mm,	Y =   -632.694  mm,	Z =   -248.200  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[478]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  84.360  mm,	Y =   -630.389  mm,	Z =   -261.973  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[479]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  95.519  mm,	Y =   -623.823  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[480]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  150.126  mm,	Y =   -592.253  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[481]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  168.419  mm,	Y =   -581.719  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[482]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.831  mm,	Y =   -560.612  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[483]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.052  mm,	Y =   -550.261  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[484]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  277.625  mm,	Y =   -518.677  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[485]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  295.801  mm,	Y =   -508.256  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[486]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  332.180  mm,	Y =   -487.237  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[487]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  422.842  mm,	Y =   -434.745  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[488]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  459.065  mm,	Y =   -413.887  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[489]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  514.184  mm,	Y =   -382.024  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[490]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  532.228  mm,	Y =   -371.647  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[491]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  550.141  mm,	Y =   -361.240  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[492]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  578.422  mm,	Y =   -345.240  mm,	Z =   -258.781  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[493]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  580.211  mm,	Y =   -368.067  mm,	Z =   -266.283  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[494]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  560.695  mm,	Y =   -379.290  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[495]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  505.985  mm,	Y =   -410.945  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[496]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  469.806  mm,	Y =   -431.829  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[497]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  396.987  mm,	Y =   -473.854  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[498]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  360.530  mm,	Y =   -494.814  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[499]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  342.478  mm,	Y =   -505.311  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[500]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  324.052  mm,	Y =   -515.696  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[501]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  306.123  mm,	Y =   -526.319  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[502]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.949  mm,	Y =   -536.712  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[503]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.698  mm,	Y =   -557.782  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[504]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.213  mm,	Y =   -578.773  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[505]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  160.535  mm,	Y =   -610.339  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[506]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  142.213  mm,	Y =   -620.805  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[507]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  106.162  mm,	Y =   -641.800  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[508]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  94.773  mm,	Y =   -648.395  mm,	Z =   -262.002  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[509]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  90.472  mm,	Y =   -650.908  mm,	Z =   -248.200  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[510]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  124.271  mm,	Y =   -631.447  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[511]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  178.773  mm,	Y =   -600.003  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[512]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.986  mm,	Y =   -589.631  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[513]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.418  mm,	Y =   -568.352  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[514]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  269.919  mm,	Y =   -547.346  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[515]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  378.875  mm,	Y =   -484.547  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[516]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  415.424  mm,	Y =   -463.320  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[517]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  433.559  mm,	Y =   -452.991  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[518]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  451.784  mm,	Y =   -442.412  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[519]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  488.126  mm,	Y =   -421.292  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[520]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  524.439  mm,	Y =   -400.389  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[521]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  542.644  mm,	Y =   -390.001  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[522]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  588.832  mm,	Y =   -363.325  mm,	Z =   -258.859  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[523]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  592.208  mm,	Y =   -361.394  mm,	Z =   -247.960  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[524]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  602.472  mm,	Y =   -379.509  mm,	Z =   -248.435  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[525]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  534.847  mm,	Y =   -418.347  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[526]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  498.274  mm,	Y =   -439.482  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[527]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  407.652  mm,	Y =   -491.986  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[528]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  389.393  mm,	Y =   -502.496  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[529]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  352.833  mm,	Y =   -523.469  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[530]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  316.604  mm,	Y =   -544.429  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[531]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  280.341  mm,	Y =   -565.474  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[532]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.658  mm,	Y =   -586.484  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[533]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.600  mm,	Y =   -596.805  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[534]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  207.565  mm,	Y =   -607.525  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[535]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  134.641  mm,	Y =   -649.517  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[536]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  116.667  mm,	Y =   -659.834  mm,	Z =   -266.999  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[537]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  100.943  mm,	Y =   -669.018  mm,	Z =   -248.233  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[538]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  105.313  mm,	Y =   -666.641  mm,	Z =   -261.991  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[539]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  152.979  mm,	Y =   -639.046  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[540]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  171.400  mm,	Y =   -628.527  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[541]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.254  mm,	Y =   -618.287  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[542]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.985  mm,	Y =   -576.181  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[543]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  298.625  mm,	Y =   -555.072  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[544]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  334.764  mm,	Y =   -534.219  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[545]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  371.261  mm,	Y =   -513.223  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[546]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  425.865  mm,	Y =   -481.595  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[547]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  443.907  mm,	Y =   -471.071  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[548]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  462.413  mm,	Y =   -460.660  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[549]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  480.379  mm,	Y =   -450.110  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[550]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  516.735  mm,	Y =   -429.024  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[551]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  553.156  mm,	Y =   -408.024  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[552]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  571.259  mm,	Y =   -397.553  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[553]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  590.661  mm,	Y =   -386.345  mm,	Z =   -266.291  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[554]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  599.439  mm,	Y =   -381.688  mm,	Z =   -258.848  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[555]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  613.031  mm,	Y =   -397.646  mm,	Z =   -248.218  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[556]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  609.662  mm,	Y =   -399.413  mm,	Z =   -258.820  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[557]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  601.279  mm,	Y =   -404.407  mm,	Z =   -266.188  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[558]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  563.475  mm,	Y =   -426.232  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[559]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  545.385  mm,	Y =   -436.480  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[560]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  527.094  mm,	Y =   -447.219  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[561]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  490.749  mm,	Y =   -468.240  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[562]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  472.511  mm,	Y =   -478.629  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[563]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  436.400  mm,	Y =   -499.595  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[564]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  417.894  mm,	Y =   -509.996  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[565]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  400.063  mm,	Y =   -520.609  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[566]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  381.734  mm,	Y =   -531.150  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[567]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  345.355  mm,	Y =   -552.038  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[568]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  327.064  mm,	Y =   -562.724  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[569]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  309.028  mm,	Y =   -573.020  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[570]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.722  mm,	Y =   -583.743  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[571]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.035  mm,	Y =   -625.659  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[572]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  181.771  mm,	Y =   -646.647  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[573]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  163.332  mm,	Y =   -657.099  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[574]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  115.766  mm,	Y =   -684.709  mm,	Z =   -261.928  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[575]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  111.446  mm,	Y =   -687.231  mm,	Z =   -248.194  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[576]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  127.130  mm,	Y =   -678.303  mm,	Z =   -266.997  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[577]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  145.400  mm,	Y =   -667.924  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[578]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.058  mm,	Y =   -636.256  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[579]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.169  mm,	Y =   -615.336  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[580]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.482  mm,	Y =   -604.846  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[581]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  272.771  mm,	Y =   -594.246  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[582]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  363.545  mm,	Y =   -541.924  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[583]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  454.522  mm,	Y =   -489.201  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[584]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  508.992  mm,	Y =   -457.956  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[585]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  582.042  mm,	Y =   -415.798  mm,	Z =   -267.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[586]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  615.515  mm,	Y =   -409.900  mm,	Z =   -257.490  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[587]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  123.196  mm,	Y =   -695.998  mm,	Z =   -259.674  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[588]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  620.538  mm,	Y =   -412.751  mm,	Z =   -246.668  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[589]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  608.041  mm,	Y =   -419.950  mm,	Z =   -263.147  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[590]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  135.813  mm,	Y =   -693.181  mm,	Z =   -263.514  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[591]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  154.251  mm,	Y =   -683.087  mm,	Z =   -263.903  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[592]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  172.187  mm,	Y =   -672.838  mm,	Z =   -263.833  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[593]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.582  mm,	Y =   -662.204  mm,	Z =   -263.818  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[594]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  208.704  mm,	Y =   -651.654  mm,	Z =   -263.960  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[595]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.972  mm,	Y =   -641.071  mm,	Z =   -263.921  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[596]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.153  mm,	Y =   -630.600  mm,	Z =   -263.916  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[597]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  263.255  mm,	Y =   -620.208  mm,	Z =   -263.839  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[598]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.558  mm,	Y =   -609.622  mm,	Z =   -263.888  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[599]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  299.655  mm,	Y =   -599.142  mm,	Z =   -263.881  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[600]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  318.008  mm,	Y =   -588.573  mm,	Z =   -263.877  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[601]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  335.973  mm,	Y =   -578.161  mm,	Z =   -263.902  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[602]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  354.125  mm,	Y =   -567.711  mm,	Z =   -263.979  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[603]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  372.539  mm,	Y =   -557.105  mm,	Z =   -263.848  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[604]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  390.681  mm,	Y =   -546.605  mm,	Z =   -263.943  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[605]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  408.686  mm,	Y =   -536.167  mm,	Z =   -263.883  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[606]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  427.152  mm,	Y =   -525.556  mm,	Z =   -263.874  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[607]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  445.340  mm,	Y =   -514.856  mm,	Z =   -264.027  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[608]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  463.420  mm,	Y =   -504.764  mm,	Z =   -263.715  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[609]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  481.657  mm,	Y =   -494.091  mm,	Z =   -263.787  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[610]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  499.751  mm,	Y =   -483.759  mm,	Z =   -263.805  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[611]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  518.153  mm,	Y =   -472.991  mm,	Z =   -263.913  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[612]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  536.095  mm,	Y =   -462.579  mm,	Z =   -263.946  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[613]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  554.182  mm,	Y =   -452.214  mm,	Z =   -263.790  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[614]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  572.413  mm,	Y =   -441.810  mm,	Z =   -263.768  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[615]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  590.873  mm,	Y =   -431.178  mm,	Z =   -263.744  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[616]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  122.498  mm,	Y =   -701.908  mm,	Z =   -247.035  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[617]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  139.304  mm,	Y =   -699.867  mm,	Z =   -248.273  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[618]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  612.672  mm,	Y =   -425.956  mm,	Z =   -248.324  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[619]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  594.237  mm,	Y =   -437.521  mm,	Z =   -248.124  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[620]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  575.935  mm,	Y =   -448.000  mm,	Z =   -248.339  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[621]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  557.988  mm,	Y =   -458.418  mm,	Z =   -248.204  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[622]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  539.693  mm,	Y =   -469.028  mm,	Z =   -248.092  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[623]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  521.416  mm,	Y =   -479.506  mm,	Z =   -248.272  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[624]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  503.337  mm,	Y =   -489.937  mm,	Z =   -248.292  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[625]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  485.444  mm,	Y =   -500.274  mm,	Z =   -248.278  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[626]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  466.882  mm,	Y =   -510.956  mm,	Z =   -248.362  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[627]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  448.850  mm,	Y =   -521.483  mm,	Z =   -248.083  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[628]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  430.684  mm,	Y =   -531.923  mm,	Z =   -248.203  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[629]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  412.531  mm,	Y =   -542.478  mm,	Z =   -248.024  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[630]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  394.227  mm,	Y =   -552.947  mm,	Z =   -248.266  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[631]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  376.065  mm,	Y =   -563.401  mm,	Z =   -248.344  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[632]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  358.095  mm,	Y =   -573.896  mm,	Z =   -248.054  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[633]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  339.863  mm,	Y =   -584.389  mm,	Z =   -248.137  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[634]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  321.342  mm,	Y =   -595.078  mm,	Z =   -248.149  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[635]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  303.180  mm,	Y =   -605.521  mm,	Z =   -248.253  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[636]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.205  mm,	Y =   -615.969  mm,	Z =   -248.086  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[637]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  266.932  mm,	Y =   -626.489  mm,	Z =   -248.162  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[638]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.685  mm,	Y =   -637.035  mm,	Z =   -248.135  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[639]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.672  mm,	Y =   -647.443  mm,	Z =   -248.118  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[640]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  212.317  mm,	Y =   -657.957  mm,	Z =   -248.322  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[641]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.250  mm,	Y =   -668.513  mm,	Z =   -248.021  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[642]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  176.040  mm,	Y =   -679.034  mm,	Z =   -248.005  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
P[643]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  157.868  mm,	Y =   -689.424  mm,	Z =   -248.251  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   90.000 deg
};
/END
