/PROG  WALL01.LS
/ATTR
OWNER       = MNEDITOR;
COMMENT     = "";
PROG_SIZE   = 636;
CREATE      = DATE 23-01-07  TIME 11:59:14;
MODIFIED    = DATE 23-01-07  TIME 12:02:18;
FILE_NAME   = ;
VERSION     = 0;
LINE_COUNT  = 4;
MEMORY_SIZE = 992;
PROTECT     = READ_WRITE;
TCD:  STACK_SIZE	= 0,
      TASK_PRIORITY	= 50,
      TIME_SLICE	= 0,
      BUSY_LAMP_OFF	= 0,
      ABORT_REQUEST	= 0,
      PAUSE_REQUEST	= 0;
DEFAULT_GROUP	= 1,*,*,*,*;
CONTROL_CODE	= 00000000 00000000;
/MN
   1:J P[1] 100% FINE    ;
   2:L P[2] 100mm/sec CNT0    ;
   3:L P[3] 100mm/sec CNT0    ;
   4:L P[4] 100mm/sec CNT0    ;
   5:L P[5] 100mm/sec CNT0    ;
   6:L P[6] 100mm/sec CNT0    ;
   7:L P[7] 100mm/sec CNT0    ;
   8:L P[8] 100mm/sec CNT0    ;
   9:L P[9] 100mm/sec CNT0    ;
   10:L P[10] 100mm/sec CNT0    ;
   11:L P[11] 100mm/sec CNT0    ;
   12:L P[12] 100mm/sec CNT0    ;
   13:L P[13] 100mm/sec CNT0    ;
   14:L P[14] 100mm/sec CNT0    ;
   15:L P[15] 100mm/sec CNT0    ;
   16:L P[16] 100mm/sec CNT0    ;
   17:L P[17] 100mm/sec CNT0    ;
   18:L P[18] 100mm/sec CNT0    ;
   19:L P[19] 100mm/sec CNT0    ;
   20:L P[20] 100mm/sec CNT0    ;
   21:L P[21] 100mm/sec CNT0    ;
   22:L P[22] 100mm/sec CNT0    ;
   23:L P[23] 100mm/sec CNT0    ;
   24:L P[24] 100mm/sec CNT0    ;
   25:L P[25] 100mm/sec CNT0    ;
   26:L P[26] 100mm/sec CNT0    ;
   27:L P[27] 100mm/sec CNT0    ;
   28:L P[28] 100mm/sec CNT0    ;
   29:L P[29] 100mm/sec CNT0    ;
   30:L P[30] 100mm/sec CNT0    ;
   31:L P[31] 100mm/sec CNT0    ;
   32:L P[32] 100mm/sec CNT0    ;
   33:L P[33] 100mm/sec CNT0    ;
   34:L P[34] 100mm/sec CNT0    ;
   35:L P[35] 100mm/sec CNT0    ;
   36:L P[36] 100mm/sec CNT0    ;
   37:L P[37] 100mm/sec CNT0    ;
   38:L P[38] 100mm/sec CNT0    ;
   39:L P[39] 100mm/sec CNT0    ;
   40:L P[40] 100mm/sec CNT0    ;
   41:L P[41] 100mm/sec CNT0    ;
   42:L P[42] 100mm/sec CNT0    ;
   43:L P[43] 100mm/sec CNT0    ;
   44:L P[44] 100mm/sec CNT0    ;
   45:L P[45] 100mm/sec CNT0    ;
   46:L P[46] 100mm/sec CNT0    ;
   47:L P[47] 100mm/sec CNT0    ;
   48:L P[48] 100mm/sec CNT0    ;
   49:L P[49] 100mm/sec CNT0    ;
   50:L P[50] 100mm/sec CNT0    ;
   51:L P[51] 100mm/sec CNT0    ;
   52:L P[52] 100mm/sec CNT0    ;
   53:L P[53] 100mm/sec CNT0    ;
   54:L P[54] 100mm/sec CNT0    ;
   55:L P[55] 100mm/sec CNT0    ;
   56:L P[56] 100mm/sec CNT0    ;
   57:L P[57] 100mm/sec CNT0    ;
   58:L P[58] 100mm/sec CNT0    ;
   59:L P[59] 100mm/sec CNT0    ;
   60:L P[60] 100mm/sec CNT0    ;
   61:L P[61] 100mm/sec CNT0    ;
   62:L P[62] 100mm/sec CNT0    ;
   63:L P[63] 100mm/sec CNT0    ;
   64:L P[64] 100mm/sec CNT0    ;
   65:L P[65] 100mm/sec CNT0    ;
   66:L P[66] 100mm/sec CNT0    ;
   67:L P[67] 100mm/sec CNT0    ;
   68:L P[68] 100mm/sec CNT0    ;
   69:L P[69] 100mm/sec CNT0    ;
   70:L P[70] 100mm/sec CNT0    ;
   71:L P[71] 100mm/sec CNT0    ;
   72:L P[72] 100mm/sec CNT0    ;
   73:L P[73] 100mm/sec CNT0    ;
   74:L P[74] 100mm/sec CNT0    ;
   75:L P[75] 100mm/sec CNT0    ;
   76:L P[76] 100mm/sec CNT0    ;
   77:L P[77] 100mm/sec CNT0    ;
   78:L P[78] 100mm/sec CNT0    ;
   79:L P[79] 100mm/sec CNT0    ;
   80:L P[80] 100mm/sec CNT0    ;
   81:L P[81] 100mm/sec CNT0    ;
   82:L P[82] 100mm/sec CNT0    ;
   83:L P[83] 100mm/sec CNT0    ;
   84:L P[84] 100mm/sec CNT0    ;
   85:L P[85] 100mm/sec CNT0    ;
   86:L P[86] 100mm/sec CNT0    ;
   87:L P[87] 100mm/sec CNT0    ;
   88:L P[88] 100mm/sec CNT0    ;
   89:L P[89] 100mm/sec CNT0    ;
   90:L P[90] 100mm/sec CNT0    ;
   91:L P[91] 100mm/sec CNT0    ;
   92:L P[92] 100mm/sec CNT0    ;
   93:L P[93] 100mm/sec CNT0    ;
   94:L P[94] 100mm/sec CNT0    ;
   95:L P[95] 100mm/sec CNT0    ;
   96:L P[96] 100mm/sec CNT0    ;
   97:L P[97] 100mm/sec CNT0    ;
   98:L P[98] 100mm/sec CNT0    ;
   99:L P[99] 100mm/sec CNT0    ;
   100:L P[100] 100mm/sec CNT0    ;
   101:L P[101] 100mm/sec CNT0    ;
   102:L P[102] 100mm/sec CNT0    ;
   103:L P[103] 100mm/sec CNT0    ;
   104:L P[104] 100mm/sec CNT0    ;
   105:L P[105] 100mm/sec CNT0    ;
   106:L P[106] 100mm/sec CNT0    ;
   107:L P[107] 100mm/sec CNT0    ;
   108:L P[108] 100mm/sec CNT0    ;
   109:L P[109] 100mm/sec CNT0    ;
   110:L P[110] 100mm/sec CNT0    ;
   111:L P[111] 100mm/sec CNT0    ;
   112:L P[112] 100mm/sec CNT0    ;
   113:L P[113] 100mm/sec CNT0    ;
   114:L P[114] 100mm/sec CNT0    ;
   115:L P[115] 100mm/sec CNT0    ;
   116:L P[116] 100mm/sec CNT0    ;
   117:L P[117] 100mm/sec CNT0    ;
   118:L P[118] 100mm/sec CNT0    ;
   119:L P[119] 100mm/sec CNT0    ;
   120:L P[120] 100mm/sec CNT0    ;
   121:L P[121] 100mm/sec CNT0    ;
   122:L P[122] 100mm/sec CNT0    ;
   123:L P[123] 100mm/sec CNT0    ;
   124:L P[124] 100mm/sec CNT0    ;
   125:L P[125] 100mm/sec CNT0    ;
   126:L P[126] 100mm/sec CNT0    ;
   127:L P[127] 100mm/sec CNT0    ;
   128:L P[128] 100mm/sec CNT0    ;
   129:L P[129] 100mm/sec CNT0    ;
   130:L P[130] 100mm/sec CNT0    ;
   131:L P[131] 100mm/sec CNT0    ;
   132:L P[132] 100mm/sec CNT0    ;
   133:L P[133] 100mm/sec CNT0    ;
   134:L P[134] 100mm/sec CNT0    ;
   135:L P[135] 100mm/sec CNT0    ;
   136:L P[136] 100mm/sec CNT0    ;
   137:L P[137] 100mm/sec CNT0    ;
   138:L P[138] 100mm/sec CNT0    ;
   139:L P[139] 100mm/sec CNT0    ;
   140:L P[140] 100mm/sec CNT0    ;
   141:L P[141] 100mm/sec CNT0    ;
   142:L P[142] 100mm/sec CNT0    ;
   143:L P[143] 100mm/sec CNT0    ;
   144:L P[144] 100mm/sec CNT0    ;
   145:L P[145] 100mm/sec CNT0    ;
   146:L P[146] 100mm/sec CNT0    ;
   147:L P[147] 100mm/sec CNT0    ;
   148:L P[148] 100mm/sec CNT0    ;
   149:L P[149] 100mm/sec CNT0    ;
   150:L P[150] 100mm/sec CNT0    ;
   151:L P[151] 100mm/sec CNT0    ;
   152:L P[152] 100mm/sec CNT0    ;
   153:L P[153] 100mm/sec CNT0    ;
   154:L P[154] 100mm/sec CNT0    ;
   155:L P[155] 100mm/sec CNT0    ;
   156:L P[156] 100mm/sec CNT0    ;
   157:L P[157] 100mm/sec CNT0    ;
   158:L P[158] 100mm/sec CNT0    ;
   159:L P[159] 100mm/sec CNT0    ;
   160:L P[160] 100mm/sec CNT0    ;
   161:L P[161] 100mm/sec CNT0    ;
   162:L P[162] 100mm/sec CNT0    ;
   163:L P[163] 100mm/sec CNT0    ;
   164:L P[164] 100mm/sec CNT0    ;
   165:L P[165] 100mm/sec CNT0    ;
   166:L P[166] 100mm/sec CNT0    ;
   167:L P[167] 100mm/sec CNT0    ;
   168:L P[168] 100mm/sec CNT0    ;
   169:L P[169] 100mm/sec CNT0    ;
   170:L P[170] 100mm/sec CNT0    ;
   171:L P[171] 100mm/sec CNT0    ;
   172:L P[172] 100mm/sec CNT0    ;
   173:L P[173] 100mm/sec CNT0    ;
   174:L P[174] 100mm/sec CNT0    ;
   175:L P[175] 100mm/sec CNT0    ;
   176:L P[176] 100mm/sec CNT0    ;
   177:L P[177] 100mm/sec CNT0    ;
   178:L P[178] 100mm/sec CNT0    ;
   179:L P[179] 100mm/sec CNT0    ;
   180:L P[180] 100mm/sec CNT0    ;
   181:L P[181] 100mm/sec CNT0    ;
   182:L P[182] 100mm/sec CNT0    ;
   183:L P[183] 100mm/sec CNT0    ;
   184:L P[184] 100mm/sec CNT0    ;
   185:L P[185] 100mm/sec CNT0    ;
   186:L P[186] 100mm/sec CNT0    ;
   187:L P[187] 100mm/sec CNT0    ;
   188:L P[188] 100mm/sec CNT0    ;
   189:L P[189] 100mm/sec CNT0    ;
   190:L P[190] 100mm/sec CNT0    ;
   191:L P[191] 100mm/sec CNT0    ;
   192:L P[192] 100mm/sec CNT0    ;
   193:L P[193] 100mm/sec CNT0    ;
   194:L P[194] 100mm/sec CNT0    ;
   195:L P[195] 100mm/sec CNT0    ;
   196:L P[196] 100mm/sec CNT0    ;
   197:L P[197] 100mm/sec CNT0    ;
   198:L P[198] 100mm/sec CNT0    ;
   199:L P[199] 100mm/sec CNT0    ;
   200:L P[200] 100mm/sec CNT0    ;
   201:L P[201] 100mm/sec CNT0    ;
   202:L P[202] 100mm/sec CNT0    ;
   203:L P[203] 100mm/sec CNT0    ;
   204:L P[204] 100mm/sec CNT0    ;
   205:L P[205] 100mm/sec CNT0    ;
   206:L P[206] 100mm/sec CNT0    ;
   207:L P[207] 100mm/sec CNT0    ;
   208:L P[208] 100mm/sec CNT0    ;
   209:L P[209] 100mm/sec CNT0    ;
   210:L P[210] 100mm/sec CNT0    ;
   211:L P[211] 100mm/sec CNT0    ;
   212:L P[212] 100mm/sec CNT0    ;
   213:L P[213] 100mm/sec CNT0    ;
   214:L P[214] 100mm/sec CNT0    ;
   215:L P[215] 100mm/sec CNT0    ;
   216:L P[216] 100mm/sec CNT0    ;
   217:L P[217] 100mm/sec CNT0    ;
   218:L P[218] 100mm/sec CNT0    ;
   219:L P[219] 100mm/sec CNT0    ;
   220:L P[220] 100mm/sec CNT0    ;
   221:L P[221] 100mm/sec CNT0    ;
   222:L P[222] 100mm/sec CNT0    ;
   223:L P[223] 100mm/sec CNT0    ;
   224:L P[224] 100mm/sec CNT0    ;
   225:L P[225] 100mm/sec CNT0    ;
   226:L P[226] 100mm/sec CNT0    ;
   227:L P[227] 100mm/sec CNT0    ;
   228:L P[228] 100mm/sec CNT0    ;
   229:L P[229] 100mm/sec CNT0    ;
   230:L P[230] 100mm/sec CNT0    ;
   231:L P[231] 100mm/sec CNT0    ;
   232:L P[232] 100mm/sec CNT0    ;
   233:L P[233] 100mm/sec CNT0    ;
   234:L P[234] 100mm/sec CNT0    ;
   235:L P[235] 100mm/sec CNT0    ;
   236:L P[236] 100mm/sec CNT0    ;
   237:L P[237] 100mm/sec CNT0    ;
   238:L P[238] 100mm/sec CNT0    ;
   239:L P[239] 100mm/sec CNT0    ;
   240:L P[240] 100mm/sec CNT0    ;
   241:L P[241] 100mm/sec CNT0    ;
   242:L P[242] 100mm/sec CNT0    ;
   243:L P[243] 100mm/sec CNT0    ;
   244:L P[244] 100mm/sec CNT0    ;
   245:L P[245] 100mm/sec CNT0    ;
   246:L P[246] 100mm/sec CNT0    ;
   247:L P[247] 100mm/sec CNT0    ;
   248:L P[248] 100mm/sec CNT0    ;
   249:L P[249] 100mm/sec CNT0    ;
   250:L P[250] 100mm/sec CNT0    ;
   251:L P[251] 100mm/sec CNT0    ;
   252:L P[252] 100mm/sec CNT0    ;
   253:L P[253] 100mm/sec CNT0    ;
   254:L P[254] 100mm/sec CNT0    ;
   255:L P[255] 100mm/sec CNT0    ;
   256:L P[256] 100mm/sec CNT0    ;
   257:L P[257] 100mm/sec CNT0    ;
   258:L P[258] 100mm/sec CNT0    ;
   259:L P[259] 100mm/sec CNT0    ;
   260:L P[260] 100mm/sec CNT0    ;
   261:L P[261] 100mm/sec CNT0    ;
   262:L P[262] 100mm/sec CNT0    ;
   263:L P[263] 100mm/sec CNT0    ;
   264:L P[264] 100mm/sec CNT0    ;
   265:L P[265] 100mm/sec CNT0    ;
   266:L P[266] 100mm/sec CNT0    ;
   267:L P[267] 100mm/sec CNT0    ;
   268:L P[268] 100mm/sec CNT0    ;
   269:L P[269] 100mm/sec CNT0    ;
   270:L P[270] 100mm/sec CNT0    ;
   271:L P[271] 100mm/sec CNT0    ;
   272:L P[272] 100mm/sec CNT0    ;
   273:L P[273] 100mm/sec CNT0    ;
   274:L P[274] 100mm/sec CNT0    ;
   275:L P[275] 100mm/sec CNT0    ;
   276:L P[276] 100mm/sec CNT0    ;
   277:L P[277] 100mm/sec CNT0    ;
   278:L P[278] 100mm/sec CNT0    ;
   279:L P[279] 100mm/sec CNT0    ;
   280:L P[280] 100mm/sec CNT0    ;
   281:L P[281] 100mm/sec CNT0    ;
   282:L P[282] 100mm/sec CNT0    ;
   283:L P[283] 100mm/sec CNT0    ;
   284:L P[284] 100mm/sec CNT0    ;
   285:L P[285] 100mm/sec CNT0    ;
   286:L P[286] 100mm/sec CNT0    ;
   287:L P[287] 100mm/sec CNT0    ;
   288:L P[288] 100mm/sec CNT0    ;
   289:L P[289] 100mm/sec CNT0    ;
   290:L P[290] 100mm/sec CNT0    ;
   291:L P[291] 100mm/sec CNT0    ;
   292:L P[292] 100mm/sec CNT0    ;
   293:L P[293] 100mm/sec CNT0    ;
   294:L P[294] 100mm/sec CNT0    ;
   295:L P[295] 100mm/sec CNT0    ;
   296:L P[296] 100mm/sec CNT0    ;
   297:L P[297] 100mm/sec CNT0    ;
   298:L P[298] 100mm/sec CNT0    ;
   299:L P[299] 100mm/sec CNT0    ;
   300:L P[300] 100mm/sec CNT0    ;
   301:L P[301] 100mm/sec CNT0    ;
   302:L P[302] 100mm/sec CNT0    ;
   303:L P[303] 100mm/sec CNT0    ;
   304:L P[304] 100mm/sec CNT0    ;
   305:L P[305] 100mm/sec CNT0    ;
   306:L P[306] 100mm/sec CNT0    ;
   307:L P[307] 100mm/sec CNT0    ;
   308:L P[308] 100mm/sec CNT0    ;
   309:L P[309] 100mm/sec CNT0    ;
   310:L P[310] 100mm/sec CNT0    ;
   311:L P[311] 100mm/sec CNT0    ;
   312:L P[312] 100mm/sec CNT0    ;
   313:L P[313] 100mm/sec CNT0    ;
   314:L P[314] 100mm/sec CNT0    ;
   315:L P[315] 100mm/sec CNT0    ;
   316:L P[316] 100mm/sec CNT0    ;
   317:L P[317] 100mm/sec CNT0    ;
   318:L P[318] 100mm/sec CNT0    ;
   319:L P[319] 100mm/sec CNT0    ;
   320:L P[320] 100mm/sec CNT0    ;
   321:L P[321] 100mm/sec CNT0    ;
   322:L P[322] 100mm/sec CNT0    ;
   323:L P[323] 100mm/sec CNT0    ;
   324:L P[324] 100mm/sec CNT0    ;
   325:L P[325] 100mm/sec CNT0    ;
   326:L P[326] 100mm/sec CNT0    ;
   327:L P[327] 100mm/sec CNT0    ;
   328:L P[328] 100mm/sec CNT0    ;
   329:L P[329] 100mm/sec CNT0    ;
   330:L P[330] 100mm/sec CNT0    ;
   331:L P[331] 100mm/sec CNT0    ;
   332:L P[332] 100mm/sec CNT0    ;
   333:L P[333] 100mm/sec CNT0    ;
   334:L P[334] 100mm/sec CNT0    ;
   335:L P[335] 100mm/sec CNT0    ;
   336:L P[336] 100mm/sec CNT0    ;
   337:L P[337] 100mm/sec CNT0    ;
   338:L P[338] 100mm/sec CNT0    ;
   339:L P[339] 100mm/sec CNT0    ;
   340:L P[340] 100mm/sec CNT0    ;
   341:L P[341] 100mm/sec CNT0    ;
   342:L P[342] 100mm/sec CNT0    ;
   343:L P[343] 100mm/sec CNT0    ;
   344:L P[344] 100mm/sec CNT0    ;
   345:L P[345] 100mm/sec CNT0    ;
   346:L P[346] 100mm/sec CNT0    ;
   347:L P[347] 100mm/sec CNT0    ;
   348:L P[348] 100mm/sec CNT0    ;
   349:L P[349] 100mm/sec CNT0    ;
   350:L P[350] 100mm/sec CNT0    ;
   351:L P[351] 100mm/sec CNT0    ;
   352:L P[352] 100mm/sec CNT0    ;
   353:L P[353] 100mm/sec CNT0    ;
   354:L P[354] 100mm/sec CNT0    ;
   355:L P[355] 100mm/sec CNT0    ;
   356:L P[356] 100mm/sec CNT0    ;
   357:L P[357] 100mm/sec CNT0    ;
   358:L P[358] 100mm/sec CNT0    ;
   359:L P[359] 100mm/sec CNT0    ;
   360:L P[360] 100mm/sec CNT0    ;
   361:L P[361] 100mm/sec CNT0    ;
   362:L P[362] 100mm/sec CNT0    ;
   363:L P[363] 100mm/sec CNT0    ;
   364:L P[364] 100mm/sec CNT0    ;
   365:L P[365] 100mm/sec CNT0    ;
   366:L P[366] 100mm/sec CNT0    ;
   367:L P[367] 100mm/sec CNT0    ;
   368:L P[368] 100mm/sec CNT0    ;
   369:L P[369] 100mm/sec CNT0    ;
   370:L P[370] 100mm/sec CNT0    ;
   371:L P[371] 100mm/sec CNT0    ;
   372:L P[372] 100mm/sec CNT0    ;
   373:L P[373] 100mm/sec CNT0    ;
   374:L P[374] 100mm/sec CNT0    ;
   375:L P[375] 100mm/sec CNT0    ;
   376:L P[376] 100mm/sec CNT0    ;
   377:L P[377] 100mm/sec CNT0    ;
   378:L P[378] 100mm/sec CNT0    ;
   379:L P[379] 100mm/sec CNT0    ;
   380:L P[380] 100mm/sec CNT0    ;
   381:L P[381] 100mm/sec CNT0    ;
   382:L P[382] 100mm/sec CNT0    ;
   383:L P[383] 100mm/sec CNT0    ;
   384:L P[384] 100mm/sec CNT0    ;
   385:L P[385] 100mm/sec CNT0    ;
   386:L P[386] 100mm/sec CNT0    ;
   387:L P[387] 100mm/sec CNT0    ;
   388:L P[388] 100mm/sec CNT0    ;
   389:L P[389] 100mm/sec CNT0    ;
   390:L P[390] 100mm/sec CNT0    ;
   391:L P[391] 100mm/sec CNT0    ;
   392:L P[392] 100mm/sec CNT0    ;
   393:L P[393] 100mm/sec CNT0    ;
   394:L P[394] 100mm/sec CNT0    ;
   395:L P[395] 100mm/sec CNT0    ;
   396:L P[396] 100mm/sec CNT0    ;
   397:L P[397] 100mm/sec CNT0    ;
   398:L P[398] 100mm/sec CNT0    ;
   399:L P[399] 100mm/sec CNT0    ;
   400:L P[400] 100mm/sec CNT0    ;
   401:L P[401] 100mm/sec CNT0    ;
   402:L P[402] 100mm/sec CNT0    ;
   403:L P[403] 100mm/sec CNT0    ;
   404:L P[404] 100mm/sec CNT0    ;
   405:L P[405] 100mm/sec CNT0    ;
   406:L P[406] 100mm/sec CNT0    ;
   407:L P[407] 100mm/sec CNT0    ;
   408:L P[408] 100mm/sec CNT0    ;
   409:L P[409] 100mm/sec CNT0    ;
   410:L P[410] 100mm/sec CNT0    ;
   411:L P[411] 100mm/sec CNT0    ;
   412:L P[412] 100mm/sec CNT0    ;
   413:L P[413] 100mm/sec CNT0    ;
   414:L P[414] 100mm/sec CNT0    ;
   415:L P[415] 100mm/sec CNT0    ;
   416:L P[416] 100mm/sec CNT0    ;
   417:L P[417] 100mm/sec CNT0    ;
   418:L P[418] 100mm/sec CNT0    ;
   419:L P[419] 100mm/sec CNT0    ;
   420:L P[420] 100mm/sec CNT0    ;
   421:L P[421] 100mm/sec CNT0    ;
   422:L P[422] 100mm/sec CNT0    ;
   423:L P[423] 100mm/sec CNT0    ;
   424:L P[424] 100mm/sec CNT0    ;
   425:L P[425] 100mm/sec CNT0    ;
   426:L P[426] 100mm/sec CNT0    ;
   427:L P[427] 100mm/sec CNT0    ;
   428:L P[428] 100mm/sec CNT0    ;
   429:L P[429] 100mm/sec CNT0    ;
   430:L P[430] 100mm/sec CNT0    ;
   431:L P[431] 100mm/sec CNT0    ;
   432:L P[432] 100mm/sec CNT0    ;
   433:L P[433] 100mm/sec CNT0    ;
   434:L P[434] 100mm/sec CNT0    ;
   435:L P[435] 100mm/sec CNT0    ;
   436:L P[436] 100mm/sec CNT0    ;
   437:L P[437] 100mm/sec CNT0    ;
   438:L P[438] 100mm/sec CNT0    ;
   439:L P[439] 100mm/sec CNT0    ;
   440:L P[440] 100mm/sec CNT0    ;
   441:L P[441] 100mm/sec CNT0    ;
   442:L P[442] 100mm/sec CNT0    ;
   443:L P[443] 100mm/sec CNT0    ;
   444:L P[444] 100mm/sec CNT0    ;
   445:L P[445] 100mm/sec CNT0    ;
   446:L P[446] 100mm/sec CNT0    ;
   447:L P[447] 100mm/sec CNT0    ;
   448:L P[448] 100mm/sec CNT0    ;
   449:L P[449] 100mm/sec CNT0    ;
   450:L P[450] 100mm/sec CNT0    ;
   451:L P[451] 100mm/sec CNT0    ;
   452:L P[452] 100mm/sec CNT0    ;
   453:L P[453] 100mm/sec CNT0    ;
   454:L P[454] 100mm/sec CNT0    ;
   455:L P[455] 100mm/sec CNT0    ;
   456:L P[456] 100mm/sec CNT0    ;
   457:L P[457] 100mm/sec CNT0    ;
   458:L P[458] 100mm/sec CNT0    ;
   459:L P[459] 100mm/sec CNT0    ;
   460:L P[460] 100mm/sec CNT0    ;
   461:L P[461] 100mm/sec CNT0    ;
   462:L P[462] 100mm/sec CNT0    ;
   463:L P[463] 100mm/sec CNT0    ;
   464:L P[464] 100mm/sec CNT0    ;
   465:L P[465] 100mm/sec CNT0    ;
   466:L P[466] 100mm/sec CNT0    ;
   467:L P[467] 100mm/sec CNT0    ;
   468:L P[468] 100mm/sec CNT0    ;
   469:L P[469] 100mm/sec CNT0    ;
   470:L P[470] 100mm/sec CNT0    ;
   471:L P[471] 100mm/sec CNT0    ;
   472:L P[472] 100mm/sec CNT0    ;
   473:L P[473] 100mm/sec CNT0    ;
   474:L P[474] 100mm/sec CNT0    ;
   475:L P[475] 100mm/sec CNT0    ;
   476:L P[476] 100mm/sec CNT0    ;
   477:L P[477] 100mm/sec CNT0    ;
   478:L P[478] 100mm/sec CNT0    ;
   479:L P[479] 100mm/sec CNT0    ;
   480:L P[480] 100mm/sec CNT0    ;
   481:L P[481] 100mm/sec CNT0    ;
   482:L P[482] 100mm/sec CNT0    ;
   483:L P[483] 100mm/sec CNT0    ;
   484:L P[484] 100mm/sec CNT0    ;
   485:L P[485] 100mm/sec CNT0    ;
   486:L P[486] 100mm/sec CNT0    ;
   487:L P[487] 100mm/sec CNT0    ;
   488:L P[488] 100mm/sec CNT0    ;
   489:L P[489] 100mm/sec CNT0    ;
   490:L P[490] 100mm/sec CNT0    ;
   491:L P[491] 100mm/sec CNT0    ;
   492:L P[492] 100mm/sec CNT0    ;
   493:L P[493] 100mm/sec CNT0    ;
   494:L P[494] 100mm/sec CNT0    ;
   495:L P[495] 100mm/sec CNT0    ;
   496:L P[496] 100mm/sec CNT0    ;
   497:L P[497] 100mm/sec CNT0    ;
   498:L P[498] 100mm/sec CNT0    ;
   499:L P[499] 100mm/sec CNT0    ;
   500:L P[500] 100mm/sec CNT0    ;
   501:L P[501] 100mm/sec CNT0    ;
   502:L P[502] 100mm/sec CNT0    ;
   503:L P[503] 100mm/sec CNT0    ;
   504:L P[504] 100mm/sec CNT0    ;
   505:L P[505] 100mm/sec CNT0    ;
   506:L P[506] 100mm/sec CNT0    ;
   507:L P[507] 100mm/sec CNT0    ;
   508:L P[508] 100mm/sec CNT0    ;
   509:L P[509] 100mm/sec CNT0    ;
   510:L P[510] 100mm/sec CNT0    ;
   511:L P[511] 100mm/sec CNT0    ;
   512:L P[512] 100mm/sec CNT0    ;
   513:L P[513] 100mm/sec CNT0    ;
   514:L P[514] 100mm/sec CNT0    ;
   515:L P[515] 100mm/sec CNT0    ;
   516:L P[516] 100mm/sec CNT0    ;
   517:L P[517] 100mm/sec CNT0    ;
   518:L P[518] 100mm/sec CNT0    ;
   519:L P[519] 100mm/sec CNT0    ;
   520:L P[520] 100mm/sec CNT0    ;
   521:L P[521] 100mm/sec CNT0    ;
   522:L P[522] 100mm/sec CNT0    ;
   523:L P[523] 100mm/sec CNT0    ;
   524:L P[524] 100mm/sec CNT0    ;
   525:L P[525] 100mm/sec CNT0    ;
   526:L P[526] 100mm/sec CNT0    ;
   527:L P[527] 100mm/sec CNT0    ;
   528:L P[528] 100mm/sec CNT0    ;
   529:L P[529] 100mm/sec CNT0    ;
   530:L P[530] 100mm/sec CNT0    ;
   531:L P[531] 100mm/sec CNT0    ;
   532:L P[532] 100mm/sec CNT0    ;
   533:L P[533] 100mm/sec CNT0    ;
   534:L P[534] 100mm/sec CNT0    ;
   535:L P[535] 100mm/sec CNT0    ;
   536:L P[536] 100mm/sec CNT0    ;
   537:L P[537] 100mm/sec CNT0    ;
   538:L P[538] 100mm/sec CNT0    ;
   539:L P[539] 100mm/sec CNT0    ;
   540:L P[540] 100mm/sec CNT0    ;
   541:L P[541] 100mm/sec CNT0    ;
   542:L P[542] 100mm/sec CNT0    ;
   543:L P[543] 100mm/sec CNT0    ;
   544:L P[544] 100mm/sec CNT0    ;
   545:L P[545] 100mm/sec CNT0    ;
   546:L P[546] 100mm/sec CNT0    ;
   547:L P[547] 100mm/sec CNT0    ;
   548:L P[548] 100mm/sec CNT0    ;
   549:L P[549] 100mm/sec CNT0    ;
   550:L P[550] 100mm/sec CNT0    ;
   551:L P[551] 100mm/sec CNT0    ;
   552:L P[552] 100mm/sec CNT0    ;
   553:L P[553] 100mm/sec CNT0    ;
   554:L P[554] 100mm/sec CNT0    ;
   555:L P[555] 100mm/sec CNT0    ;
   556:L P[556] 100mm/sec CNT0    ;
   557:L P[557] 100mm/sec CNT0    ;
   558:L P[558] 100mm/sec CNT0    ;
   559:L P[559] 100mm/sec CNT0    ;
   560:L P[560] 100mm/sec CNT0    ;
   561:L P[561] 100mm/sec CNT0    ;
   562:L P[562] 100mm/sec CNT0    ;
   563:L P[563] 100mm/sec CNT0    ;
   564:L P[564] 100mm/sec CNT0    ;
   565:L P[565] 100mm/sec CNT0    ;
   566:L P[566] 100mm/sec CNT0    ;
   567:L P[567] 100mm/sec CNT0    ;
   568:L P[568] 100mm/sec CNT0    ;
   569:L P[569] 100mm/sec CNT0    ;
   570:L P[570] 100mm/sec CNT0    ;
   571:L P[571] 100mm/sec CNT0    ;
   572:L P[572] 100mm/sec CNT0    ;
   573:L P[573] 100mm/sec CNT0    ;
   574:L P[574] 100mm/sec CNT0    ;
   575:L P[575] 100mm/sec CNT0    ;
   576:L P[576] 100mm/sec CNT0    ;
   577:L P[577] 100mm/sec CNT0    ;
   578:L P[578] 100mm/sec CNT0    ;
   579:L P[579] 100mm/sec CNT0    ;
   580:L P[580] 100mm/sec CNT0    ;
   581:L P[581] 100mm/sec CNT0    ;
   582:L P[582] 100mm/sec CNT0    ;
   583:L P[583] 100mm/sec CNT0    ;
   584:L P[584] 100mm/sec CNT0    ;
   585:L P[585] 100mm/sec CNT0    ;
   586:L P[586] 100mm/sec CNT0    ;
   587:L P[587] 100mm/sec CNT0    ;
   588:L P[588] 100mm/sec CNT0    ;
   589:L P[589] 100mm/sec CNT0    ;
   590:L P[590] 100mm/sec CNT0    ;
   591:L P[591] 100mm/sec CNT0    ;
   592:L P[592] 100mm/sec CNT0    ;
   593:L P[593] 100mm/sec CNT0    ;
   594:L P[594] 100mm/sec CNT0    ;
   595:L P[595] 100mm/sec CNT0    ;
   596:L P[596] 100mm/sec CNT0    ;
   597:L P[597] 100mm/sec CNT0    ;
   598:L P[598] 100mm/sec CNT0    ;
   599:L P[599] 100mm/sec CNT0    ;
   600:L P[600] 100mm/sec CNT0    ;
   601:L P[601] 100mm/sec CNT0    ;
   602:L P[602] 100mm/sec CNT0    ;
   603:L P[603] 100mm/sec CNT0    ;
   604:L P[604] 100mm/sec CNT0    ;
   605:L P[605] 100mm/sec CNT0    ;
   606:L P[606] 100mm/sec CNT0    ;
   607:L P[607] 100mm/sec CNT0    ;
   608:L P[608] 100mm/sec CNT0    ;
   609:L P[609] 100mm/sec CNT0    ;
   610:L P[610] 100mm/sec CNT0    ;
   611:L P[611] 100mm/sec CNT0    ;
   612:L P[612] 100mm/sec CNT0    ;
   613:L P[613] 100mm/sec CNT0    ;
   614:L P[614] 100mm/sec CNT0    ;
   615:L P[615] 100mm/sec CNT0    ;
   616:L P[616] 100mm/sec CNT0    ;
   617:L P[617] 100mm/sec CNT0    ;
   618:L P[618] 100mm/sec CNT0    ;
   619:L P[619] 100mm/sec CNT0    ;
   620:L P[620] 100mm/sec CNT0    ;
   621:L P[621] 100mm/sec CNT0    ;
   622:L P[622] 100mm/sec CNT0    ;
   623:L P[623] 100mm/sec CNT0    ;
   624:L P[624] 100mm/sec CNT0    ;
   625:L P[625] 100mm/sec CNT0    ;
   626:L P[626] 100mm/sec CNT0    ;
   627:L P[627] 100mm/sec CNT0    ;
   628:L P[628] 100mm/sec CNT0    ;
   629:L P[629] 100mm/sec CNT0    ;
   630:L P[630] 100mm/sec CNT0    ;
   631:L P[631] 100mm/sec CNT0    ;
   632:L P[632] 100mm/sec CNT0    ;
   633:L P[633] 100mm/sec CNT0    ;
   634:L P[634] 100mm/sec CNT0    ;
   635:L P[635] 100mm/sec CNT0    ;
   636:L P[636] 100mm/sec CNT0    ;
   637:L P[637] 100mm/sec CNT0    ;
   638:L P[638] 100mm/sec CNT0    ;
   639:L P[639] 100mm/sec CNT0    ;
   640:L P[640] 100mm/sec CNT0    ;
   641:L P[641] 100mm/sec CNT0    ;
   642:L P[642] 100mm/sec CNT0    ;
   643:L P[643] 100mm/sec CNT0    ;
   644:L P[644] 100mm/sec CNT0    ;
   645:L P[645] 100mm/sec CNT0    ;
   646:L P[646] 100mm/sec CNT0    ;
   647:L P[647] 100mm/sec CNT0    ;
   648:L P[648] 100mm/sec CNT0    ;
   649:L P[649] 100mm/sec CNT0    ;
   650:L P[650] 100mm/sec CNT0    ;
   651:L P[651] 100mm/sec CNT0    ;
   652:L P[652] 100mm/sec CNT0    ;
   653:L P[653] 100mm/sec CNT0    ;
   654:L P[654] 100mm/sec CNT0    ;
   655:L P[655] 100mm/sec CNT0    ;
   656:L P[656] 100mm/sec CNT0    ;
   657:L P[657] 100mm/sec CNT0    ;
   658:L P[658] 100mm/sec CNT0    ;
   659:L P[659] 100mm/sec CNT0    ;
   660:L P[660] 100mm/sec CNT0    ;
   661:L P[661] 100mm/sec CNT0    ;
   662:L P[662] 100mm/sec CNT0    ;
   663:L P[663] 100mm/sec CNT0    ;
   664:L P[664] 100mm/sec CNT0    ;
   665:L P[665] 100mm/sec CNT0    ;
   666:L P[666] 100mm/sec CNT0    ;
   667:L P[667] 100mm/sec CNT0    ;
   668:L P[668] 100mm/sec CNT0    ;
   669:L P[669] 100mm/sec CNT0    ;
   670:L P[670] 100mm/sec CNT0    ;
   671:L P[671] 100mm/sec CNT0    ;
   672:L P[672] 100mm/sec CNT0    ;
   673:L P[673] 100mm/sec CNT0    ;
   674:L P[674] 100mm/sec CNT0    ;
   675:L P[675] 100mm/sec CNT0    ;
   676:L P[676] 100mm/sec CNT0    ;
   677:L P[677] 100mm/sec CNT0    ;
   678:L P[678] 100mm/sec CNT0    ;
   679:L P[679] 100mm/sec CNT0    ;
   680:L P[680] 100mm/sec CNT0    ;
   681:L P[681] 100mm/sec CNT0    ;
   682:L P[682] 100mm/sec CNT0    ;
   683:L P[683] 100mm/sec CNT0    ;
   684:L P[684] 100mm/sec CNT0    ;
   685:L P[685] 100mm/sec CNT0    ;
   686:L P[686] 100mm/sec CNT0    ;
   687:L P[687] 100mm/sec CNT0    ;
   688:L P[688] 100mm/sec CNT0    ;
   689:L P[689] 100mm/sec CNT0    ;
   690:L P[690] 100mm/sec CNT0    ;
   691:L P[691] 100mm/sec CNT0    ;
   692:L P[692] 100mm/sec CNT0    ;
   693:L P[693] 100mm/sec CNT0    ;
   694:L P[694] 100mm/sec CNT0    ;
   695:L P[695] 100mm/sec CNT0    ;
   696:L P[696] 100mm/sec CNT0    ;
   697:L P[697] 100mm/sec CNT0    ;
   698:L P[698] 100mm/sec CNT0    ;
   699:L P[699] 100mm/sec CNT0    ;
   700:L P[700] 100mm/sec CNT0    ;
   701:L P[701] 100mm/sec CNT0    ;
   702:L P[702] 100mm/sec CNT0    ;
   703:L P[703] 100mm/sec CNT0    ;
   704:L P[704] 100mm/sec CNT0    ;
   705:L P[705] 100mm/sec CNT0    ;
   706:L P[706] 100mm/sec CNT0    ;
   707:L P[707] 100mm/sec CNT0    ;
   708:L P[708] 100mm/sec CNT0    ;
   709:L P[709] 100mm/sec CNT0    ;
   710:L P[710] 100mm/sec CNT0    ;
   711:L P[711] 100mm/sec CNT0    ;
   712:L P[712] 100mm/sec CNT0    ;
   713:L P[713] 100mm/sec CNT0    ;
   714:L P[714] 100mm/sec CNT0    ;
   715:L P[715] 100mm/sec CNT0    ;
   716:L P[716] 100mm/sec CNT0    ;
   717:L P[717] 100mm/sec CNT0    ;
   718:L P[718] 100mm/sec CNT0    ;
   719:L P[719] 100mm/sec CNT0    ;
   720:L P[720] 100mm/sec CNT0    ;
   721:L P[721] 100mm/sec CNT0    ;
   722:L P[722] 100mm/sec CNT0    ;
   723:L P[723] 100mm/sec CNT0    ;
   724:L P[724] 100mm/sec CNT0    ;
   725:L P[725] 100mm/sec CNT0    ;
   726:L P[726] 100mm/sec CNT0    ;
   727:L P[727] 100mm/sec CNT0    ;
   728:L P[728] 100mm/sec CNT0    ;
   729:L P[729] 100mm/sec CNT0    ;
   730:L P[730] 100mm/sec CNT0    ;
   731:L P[731] 100mm/sec CNT0    ;
   732:L P[732] 100mm/sec CNT0    ;
   733:L P[733] 100mm/sec CNT0    ;
   734:L P[734] 100mm/sec CNT0    ;
   735:L P[735] 100mm/sec CNT0    ;
   736:L P[736] 100mm/sec CNT0    ;
   737:L P[737] 100mm/sec CNT0    ;
   738:L P[738] 100mm/sec CNT0    ;
   739:L P[739] 100mm/sec CNT0    ;
   740:L P[740] 100mm/sec CNT0    ;
   741:L P[741] 100mm/sec CNT0    ;
   742:L P[742] 100mm/sec CNT0    ;
   743:L P[743] 100mm/sec CNT0    ;
   744:L P[744] 100mm/sec CNT0    ;
   745:L P[745] 100mm/sec CNT0    ;
   746:L P[746] 100mm/sec CNT0    ;
   747:L P[747] 100mm/sec CNT0    ;
   748:L P[748] 100mm/sec CNT0    ;
   749:L P[749] 100mm/sec CNT0    ;
   750:L P[750] 100mm/sec CNT0    ;
   751:L P[751] 100mm/sec CNT0    ;
   752:L P[752] 100mm/sec CNT0    ;
   753:L P[753] 100mm/sec CNT0    ;
   754:L P[754] 100mm/sec CNT0    ;
   755:L P[755] 100mm/sec CNT0    ;
   756:L P[756] 100mm/sec CNT0    ;
   757:L P[757] 100mm/sec CNT0    ;
   758:L P[758] 100mm/sec CNT0    ;
   759:L P[759] 100mm/sec CNT0    ;
   760:L P[760] 100mm/sec CNT0    ;
   761:L P[761] 100mm/sec CNT0    ;
   762:L P[762] 100mm/sec CNT0    ;
   763:L P[763] 100mm/sec CNT0    ;
   764:L P[764] 100mm/sec CNT0    ;
   765:L P[765] 100mm/sec CNT0    ;
   766:L P[766] 100mm/sec CNT0    ;
   767:L P[767] 100mm/sec CNT0    ;
   768:L P[768] 100mm/sec CNT0    ;
   769:L P[769] 100mm/sec CNT0    ;
   770:L P[770] 100mm/sec CNT0    ;
   771:L P[771] 100mm/sec CNT0    ;
   772:L P[772] 100mm/sec CNT0    ;
   773:L P[773] 100mm/sec CNT0    ;
   774:L P[774] 100mm/sec CNT0    ;
   775:L P[775] 100mm/sec CNT0    ;
   776:L P[776] 100mm/sec CNT0    ;
   777:L P[777] 100mm/sec CNT0    ;
   778:L P[778] 100mm/sec CNT0    ;
   779:L P[779] 100mm/sec CNT0    ;
   780:L P[780] 100mm/sec CNT0    ;
   781:L P[781] 100mm/sec CNT0    ;
   782:L P[782] 100mm/sec CNT0    ;
   783:L P[783] 100mm/sec CNT0    ;
   784:L P[784] 100mm/sec CNT0    ;
   785:L P[785] 100mm/sec CNT0    ;
   786:L P[786] 100mm/sec CNT0    ;
   787:L P[787] 100mm/sec CNT0    ;
   788:L P[788] 100mm/sec CNT0    ;
   789:L P[789] 100mm/sec CNT0    ;
   790:L P[790] 100mm/sec CNT0    ;
   791:L P[791] 100mm/sec CNT0    ;
   792:L P[792] 100mm/sec CNT0    ;
   793:L P[793] 100mm/sec CNT0    ;
   794:L P[794] 100mm/sec CNT0    ;
   795:L P[795] 100mm/sec CNT0    ;
   796:L P[796] 100mm/sec CNT0    ;
   797:L P[797] 100mm/sec CNT0    ;
   798:L P[798] 100mm/sec CNT0    ;
   799:L P[799] 100mm/sec CNT0    ;
   800:L P[800] 100mm/sec CNT0    ;
   801:L P[801] 100mm/sec CNT0    ;
   802:L P[802] 100mm/sec CNT0    ;
   803:L P[803] 100mm/sec CNT0    ;
   804:L P[804] 100mm/sec CNT0    ;
   805:L P[805] 100mm/sec CNT0    ;
   806:L P[806] 100mm/sec CNT0    ;
   807:L P[807] 100mm/sec CNT0    ;
   808:L P[808] 100mm/sec CNT0    ;
   809:L P[809] 100mm/sec CNT0    ;
   810:L P[810] 100mm/sec CNT0    ;
   811:L P[811] 100mm/sec CNT0    ;
   812:L P[812] 100mm/sec CNT0    ;
   813:L P[813] 100mm/sec CNT0    ;
   814:L P[814] 100mm/sec CNT0    ;
   815:L P[815] 100mm/sec CNT0    ;
   816:L P[816] 100mm/sec CNT0    ;
   817:L P[817] 100mm/sec CNT0    ;
   818:L P[818] 100mm/sec CNT0    ;
   819:L P[819] 100mm/sec CNT0    ;
   820:L P[820] 100mm/sec CNT0    ;
   821:L P[821] 100mm/sec CNT0    ;
   822:L P[822] 100mm/sec CNT0    ;
   823:L P[823] 100mm/sec CNT0    ;
   824:L P[824] 100mm/sec CNT0    ;
   825:L P[825] 100mm/sec CNT0    ;
   826:L P[826] 100mm/sec CNT0    ;
   827:L P[827] 100mm/sec CNT0    ;
   828:L P[828] 100mm/sec CNT0    ;
   829:L P[829] 100mm/sec CNT0    ;
   830:L P[830] 100mm/sec CNT0    ;
   831:L P[831] 100mm/sec CNT0    ;
   832:L P[832] 100mm/sec CNT0    ;
   833:L P[833] 100mm/sec CNT0    ;
   834:L P[834] 100mm/sec CNT0    ;
   835:L P[835] 100mm/sec CNT0    ;
   836:L P[836] 100mm/sec CNT0    ;
   837:L P[837] 100mm/sec CNT0    ;
   838:L P[838] 100mm/sec CNT0    ;
   839:L P[839] 100mm/sec CNT0    ;
   840:L P[840] 100mm/sec CNT0    ;
   841:L P[841] 100mm/sec CNT0    ;
   842:L P[842] 100mm/sec CNT0    ;
   843:L P[843] 100mm/sec CNT0    ;
   844:L P[844] 100mm/sec CNT0    ;
   845:L P[845] 100mm/sec CNT0    ;
   846:L P[846] 100mm/sec CNT0    ;
   847:L P[847] 100mm/sec CNT0    ;
   848:L P[848] 100mm/sec CNT0    ;
   849:L P[849] 100mm/sec CNT0    ;
   850:L P[850] 100mm/sec CNT0    ;
   851:L P[851] 100mm/sec CNT0    ;
   852:L P[852] 100mm/sec CNT0    ;
   853:L P[853] 100mm/sec CNT0    ;
   854:L P[854] 100mm/sec CNT0    ;
   855:L P[855] 100mm/sec CNT0    ;
   856:L P[856] 100mm/sec CNT0    ;
/POS
P[1]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.000  mm,	Y =   -370.000  mm,	Z =   -170.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[2]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.873  mm,	Y =   -362.007  mm,	Z =   -246.997  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[3]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.595  mm,	Y =   -362.241  mm,	Z =   -247.906  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[4]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.327  mm,	Y =   -362.396  mm,	Z =   -247.902  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[5]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.721  mm,	Y =   -362.668  mm,	Z =   -246.947  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[6]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.754  mm,	Y =   -362.726  mm,	Z =   -247.894  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[7]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.458  mm,	Y =   -362.893  mm,	Z =   -247.844  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[8]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.617  mm,	Y =   -363.304  mm,	Z =   -246.921  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[9]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.370  mm,	Y =   -363.518  mm,	Z =   -247.811  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[10]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.863  mm,	Y =   -363.814  mm,	Z =   -247.846  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[11]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.759  mm,	Y =   -363.807  mm,	Z =   -247.014  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[12]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.568  mm,	Y =   -363.984  mm,	Z =   -247.844  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[13]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.221  mm,	Y =   -364.117  mm,	Z =   -247.005  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[14]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.930  mm,	Y =   -364.338  mm,	Z =   -247.665  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[15]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.693  mm,	Y =   -364.418  mm,	Z =   -246.964  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[16]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.464  mm,	Y =   -364.622  mm,	Z =   -247.854  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[17]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.166  mm,	Y =   -364.787  mm,	Z =   -247.765  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[18]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.087  mm,	Y =   -364.769  mm,	Z =   -246.981  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[19]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.616  mm,	Y =   -365.112  mm,	Z =   -247.852  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[20]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.313  mm,	Y =   -365.287  mm,	Z =   -247.860  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[21]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.020  mm,	Y =   -365.455  mm,	Z =   -247.841  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[22]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.793  mm,	Y =   -365.589  mm,	Z =   -247.875  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[23]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.414  mm,	Y =   -365.734  mm,	Z =   -246.960  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[24]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.898  mm,	Y =   -366.030  mm,	Z =   -246.938  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[25]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.943  mm,	Y =   -366.072  mm,	Z =   -247.782  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[26]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.617  mm,	Y =   -366.193  mm,	Z =   -246.947  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[27]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.667  mm,	Y =   -366.238  mm,	Z =   -247.873  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[28]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.308  mm,	Y =   -366.369  mm,	Z =   -246.921  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[29]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.361  mm,	Y =   -366.417  mm,	Z =   -247.895  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[30]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.788  mm,	Y =   -366.687  mm,	Z =   -247.130  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[31]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.595  mm,	Y =   -366.860  mm,	Z =   -247.904  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[32]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.630  mm,	Y =   -367.343  mm,	Z =   -246.982  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[33]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.391  mm,	Y =   -367.481  mm,	Z =   -246.983  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[34]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.091  mm,	Y =   -367.659  mm,	Z =   -247.044  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[35]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  224.929  mm,	Y =   -367.812  mm,	Z =   -247.780  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[36]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  224.640  mm,	Y =   -367.986  mm,	Z =   -247.870  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[37]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.719  mm,	Y =   -368.451  mm,	Z =   -247.037  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[38]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.396  mm,	Y =   -368.631  mm,	Z =   -246.955  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[39]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.197  mm,	Y =   -368.810  mm,	Z =   -247.746  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[40]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.654  mm,	Y =   -369.132  mm,	Z =   -247.862  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[41]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.328  mm,	Y =   -369.246  mm,	Z =   -246.931  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[42]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.010  mm,	Y =   -369.430  mm,	Z =   -246.939  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[43]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.747  mm,	Y =   -369.587  mm,	Z =   -247.015  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[44]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.823  mm,	Y =   -369.608  mm,	Z =   -247.820  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[45]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.442  mm,	Y =   -369.762  mm,	Z =   -246.993  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[46]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.203  mm,	Y =   -369.906  mm,	Z =   -247.070  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[47]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.242  mm,	Y =   -369.946  mm,	Z =   -247.835  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[48]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  220.925  mm,	Y =   -370.059  mm,	Z =   -246.976  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[49]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  220.959  mm,	Y =   -370.111  mm,	Z =   -247.866  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[50]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  220.722  mm,	Y =   -370.250  mm,	Z =   -247.886  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[51]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  220.419  mm,	Y =   -370.415  mm,	Z =   -247.764  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[52]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.547  mm,	Y =   -370.864  mm,	Z =   -247.083  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[53]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.250  mm,	Y =   -371.030  mm,	Z =   -247.029  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[54]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.961  mm,	Y =   -371.192  mm,	Z =   -246.958  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[55]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.687  mm,	Y =   -371.348  mm,	Z =   -246.926  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[56]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.123  mm,	Y =   -371.684  mm,	Z =   -246.970  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[57]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.229  mm,	Y =   -371.710  mm,	Z =   -247.899  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[58]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.941  mm,	Y =   -372.007  mm,	Z =   -246.925  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[59]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.092  mm,	Y =   -372.024  mm,	Z =   -247.893  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[60]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.172  mm,	Y =   -372.174  mm,	Z =   -247.663  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[61]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.378  mm,	Y =   -372.263  mm,	Z =   -247.855  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[62]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.557  mm,	Y =   -375.604  mm,	Z =   -247.005  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[63]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.546  mm,	Y =   -375.695  mm,	Z =   -247.909  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[64]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.935  mm,	Y =   -376.182  mm,	Z =   -246.980  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[65]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.043  mm,	Y =   -376.169  mm,	Z =   -247.892  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[66]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.616  mm,	Y =   -376.494  mm,	Z =   -246.962  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[67]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.227  mm,	Y =   -376.979  mm,	Z =   -246.947  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[68]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.160  mm,	Y =   -377.180  mm,	Z =   -247.833  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[69]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.635  mm,	Y =   -378.005  mm,	Z =   -247.886  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[70]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.121  mm,	Y =   -378.927  mm,	Z =   -247.040  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[71]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.795  mm,	Y =   -380.098  mm,	Z =   -246.930  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[72]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.720  mm,	Y =   -380.712  mm,	Z =   -246.957  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[73]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.736  mm,	Y =   -381.356  mm,	Z =   -247.022  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[74]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.765  mm,	Y =   -381.753  mm,	Z =   -246.999  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[75]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.947  mm,	Y =   -382.249  mm,	Z =   -247.818  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[76]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.140  mm,	Y =   -382.859  mm,	Z =   -247.918  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[77]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.399  mm,	Y =   -383.449  mm,	Z =   -247.757  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[78]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.437  mm,	Y =   -383.663  mm,	Z =   -246.924  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[79]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.780  mm,	Y =   -384.257  mm,	Z =   -246.994  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[80]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.122  mm,	Y =   -384.857  mm,	Z =   -246.933  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[81]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.454  mm,	Y =   -385.432  mm,	Z =   -246.935  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[82]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.521  mm,	Y =   -385.414  mm,	Z =   -247.895  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[83]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.837  mm,	Y =   -386.094  mm,	Z =   -246.944  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[84]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.545  mm,	Y =   -387.189  mm,	Z =   -247.889  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[85]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.554  mm,	Y =   -387.306  mm,	Z =   -247.151  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[86]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.940  mm,	Y =   -387.886  mm,	Z =   -247.792  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[87]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  191.241  mm,	Y =   -388.517  mm,	Z =   -247.004  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[88]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  191.593  mm,	Y =   -389.132  mm,	Z =   -246.959  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[89]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  191.975  mm,	Y =   -389.789  mm,	Z =   -246.997  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[90]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  192.358  mm,	Y =   -390.452  mm,	Z =   -247.001  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[91]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  192.418  mm,	Y =   -390.429  mm,	Z =   -247.910  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[92]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  193.085  mm,	Y =   -391.590  mm,	Z =   -247.869  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[93]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  193.470  mm,	Y =   -392.251  mm,	Z =   -247.913  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[94]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.169  mm,	Y =   -393.596  mm,	Z =   -246.941  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[95]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.525  mm,	Y =   -394.215  mm,	Z =   -246.931  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[96]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.937  mm,	Y =   -394.800  mm,	Z =   -247.844  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[97]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  195.584  mm,	Y =   -396.048  mm,	Z =   -246.942  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[98]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.060  mm,	Y =   -396.741  mm,	Z =   -247.887  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[99]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.349  mm,	Y =   -397.249  mm,	Z =   -247.826  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[100]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.335  mm,	Y =   -397.344  mm,	Z =   -246.969  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[101]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.072  mm,	Y =   -398.503  mm,	Z =   -247.809  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[102]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.430  mm,	Y =   -399.130  mm,	Z =   -247.761  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[103]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.386  mm,	Y =   -399.168  mm,	Z =   -246.940  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[104]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.736  mm,	Y =   -399.776  mm,	Z =   -246.939  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[105]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.843  mm,	Y =   -399.832  mm,	Z =   -247.859  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[106]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  198.864  mm,	Y =   -401.709  mm,	Z =   -247.088  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[107]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.236  mm,	Y =   -402.261  mm,	Z =   -247.747  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[108]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.946  mm,	Y =   -403.467  mm,	Z =   -247.912  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[109]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.937  mm,	Y =   -403.583  mm,	Z =   -246.971  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[110]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.386  mm,	Y =   -404.230  mm,	Z =   -247.902  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[111]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.726  mm,	Y =   -404.841  mm,	Z =   -247.741  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[112]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.067  mm,	Y =   -405.426  mm,	Z =   -247.783  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[113]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.390  mm,	Y =   -405.981  mm,	Z =   -247.821  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[114]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.749  mm,	Y =   -406.717  mm,	Z =   -247.001  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[115]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  202.072  mm,	Y =   -407.275  mm,	Z =   -247.017  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[116]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  202.130  mm,	Y =   -407.275  mm,	Z =   -247.731  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[117]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  202.826  mm,	Y =   -408.345  mm,	Z =   -247.813  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[118]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  202.859  mm,	Y =   -408.505  mm,	Z =   -246.934  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[119]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  203.342  mm,	Y =   -408.934  mm,	Z =   -247.801  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[120]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  203.353  mm,	Y =   -409.038  mm,	Z =   -246.975  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[121]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  203.771  mm,	Y =   -409.408  mm,	Z =   -247.046  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[122]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.062  mm,	Y =   -409.515  mm,	Z =   -247.872  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[123]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.584  mm,	Y =   -409.823  mm,	Z =   -247.876  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[124]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  205.243  mm,	Y =   -410.182  mm,	Z =   -247.087  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[125]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  205.676  mm,	Y =   -410.268  mm,	Z =   -247.812  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[126]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  206.207  mm,	Y =   -410.455  mm,	Z =   -246.928  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[127]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  206.350  mm,	Y =   -410.399  mm,	Z =   -247.830  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[128]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  207.317  mm,	Y =   -410.562  mm,	Z =   -246.950  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[129]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  208.598  mm,	Y =   -410.407  mm,	Z =   -247.850  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[130]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  208.549  mm,	Y =   -410.483  mm,	Z =   -246.989  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[131]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  209.245  mm,	Y =   -410.369  mm,	Z =   -247.036  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[132]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  209.897  mm,	Y =   -410.119  mm,	Z =   -247.902  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[133]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.278  mm,	Y =   -387.254  mm,	Z =   -247.824  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[134]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.287  mm,	Y =   -387.951  mm,	Z =   -247.880  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[135]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.247  mm,	Y =   -388.102  mm,	Z =   -247.011  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[136]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.428  mm,	Y =   -388.047  mm,	Z =   -247.918  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[137]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.633  mm,	Y =   -388.015  mm,	Z =   -247.788  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[138]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.942  mm,	Y =   -387.846  mm,	Z =   -247.860  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[139]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.895  mm,	Y =   -387.942  mm,	Z =   -246.994  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[140]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.227  mm,	Y =   -387.678  mm,	Z =   -247.893  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[141]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.452  mm,	Y =   -387.614  mm,	Z =   -247.070  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[142]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.695  mm,	Y =   -387.485  mm,	Z =   -246.941  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[143]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.969  mm,	Y =   -387.324  mm,	Z =   -246.968  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[144]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.052  mm,	Y =   -387.203  mm,	Z =   -247.880  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[145]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.887  mm,	Y =   -386.725  mm,	Z =   -247.823  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[146]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.155  mm,	Y =   -386.566  mm,	Z =   -247.883  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[147]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.418  mm,	Y =   -386.411  mm,	Z =   -247.921  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[148]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.688  mm,	Y =   -386.327  mm,	Z =   -247.036  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[149]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.949  mm,	Y =   -386.182  mm,	Z =   -246.951  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[150]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.490  mm,	Y =   -385.802  mm,	Z =   -247.796  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[151]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.480  mm,	Y =   -385.878  mm,	Z =   -246.927  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[152]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.764  mm,	Y =   -385.710  mm,	Z =   -246.974  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[153]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.067  mm,	Y =   -385.535  mm,	Z =   -246.977  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[154]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.380  mm,	Y =   -385.278  mm,	Z =   -247.916  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[155]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.383  mm,	Y =   -385.357  mm,	Z =   -246.925  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[156]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.651  mm,	Y =   -385.133  mm,	Z =   -247.776  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[157]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.921  mm,	Y =   -385.038  mm,	Z =   -247.021  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[158]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.191  mm,	Y =   -384.884  mm,	Z =   -247.004  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[159]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.428  mm,	Y =   -384.746  mm,	Z =   -247.021  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[160]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.711  mm,	Y =   -384.579  mm,	Z =   -247.064  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[161]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.579  mm,	Y =   -384.083  mm,	Z =   -246.996  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[162]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.615  mm,	Y =   -383.997  mm,	Z =   -247.798  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[163]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.877  mm,	Y =   -383.907  mm,	Z =   -247.033  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[164]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.413  mm,	Y =   -383.542  mm,	Z =   -247.739  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[165]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.678  mm,	Y =   -383.376  mm,	Z =   -247.887  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[166]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.976  mm,	Y =   -383.213  mm,	Z =   -247.790  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[167]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.245  mm,	Y =   -383.122  mm,	Z =   -246.981  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[168]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.516  mm,	Y =   -382.964  mm,	Z =   -246.998  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[169]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.793  mm,	Y =   -382.807  mm,	Z =   -246.967  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[170]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.068  mm,	Y =   -382.576  mm,	Z =   -247.860  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[171]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.375  mm,	Y =   -382.396  mm,	Z =   -247.902  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[172]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.397  mm,	Y =   -382.458  mm,	Z =   -246.975  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[173]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.624  mm,	Y =   -382.255  mm,	Z =   -247.865  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[174]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.860  mm,	Y =   -382.114  mm,	Z =   -247.919  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[175]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.942  mm,	Y =   -382.144  mm,	Z =   -246.963  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[176]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.234  mm,	Y =   -381.974  mm,	Z =   -246.981  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[177]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.468  mm,	Y =   -381.765  mm,	Z =   -247.895  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[178]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.713  mm,	Y =   -381.628  mm,	Z =   -247.843  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[179]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.015  mm,	Y =   -381.522  mm,	Z =   -246.991  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[180]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.294  mm,	Y =   -381.353  mm,	Z =   -247.085  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[181]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.321  mm,	Y =   -381.275  mm,	Z =   -247.865  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[182]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.577  mm,	Y =   -381.199  mm,	Z =   -246.976  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[183]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.625  mm,	Y =   -381.096  mm,	Z =   -247.902  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[184]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.869  mm,	Y =   -380.965  mm,	Z =   -247.781  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[185]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.156  mm,	Y =   -380.792  mm,	Z =   -247.875  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[186]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.717  mm,	Y =   -380.534  mm,	Z =   -247.061  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[187]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.983  mm,	Y =   -380.391  mm,	Z =   -246.924  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[188]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.228  mm,	Y =   -380.243  mm,	Z =   -247.002  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[189]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.777  mm,	Y =   -379.854  mm,	Z =   -247.896  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[190]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.129  mm,	Y =   -379.728  mm,	Z =   -246.937  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[191]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.353  mm,	Y =   -379.521  mm,	Z =   -247.906  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[192]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.380  mm,	Y =   -379.584  mm,	Z =   -246.934  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[193]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.880  mm,	Y =   -379.219  mm,	Z =   -247.880  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[194]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.932  mm,	Y =   -379.260  mm,	Z =   -246.989  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[195]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.214  mm,	Y =   -379.102  mm,	Z =   -246.928  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[196]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.420  mm,	Y =   -378.909  mm,	Z =   -247.848  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[197]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.506  mm,	Y =   -378.931  mm,	Z =   -246.964  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[198]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.743  mm,	Y =   -378.717  mm,	Z =   -247.917  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[199]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.298  mm,	Y =   -378.476  mm,	Z =   -246.942  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[200]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.577  mm,	Y =   -378.312  mm,	Z =   -246.973  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[201]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.166  mm,	Y =   -377.976  mm,	Z =   -246.927  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[202]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.461  mm,	Y =   -377.796  mm,	Z =   -247.036  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[203]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.660  mm,	Y =   -377.615  mm,	Z =   -247.864  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[204]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.850  mm,	Y =   -376.997  mm,	Z =   -247.002  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[205]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.329  mm,	Y =   -376.648  mm,	Z =   -247.899  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[206]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.422  mm,	Y =   -376.671  mm,	Z =   -246.951  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[207]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.628  mm,	Y =   -376.478  mm,	Z =   -247.869  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[208]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.158  mm,	Y =   -376.171  mm,	Z =   -247.881  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[209]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.248  mm,	Y =   -376.192  mm,	Z =   -246.987  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[210]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.457  mm,	Y =   -375.997  mm,	Z =   -247.907  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[211]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.702  mm,	Y =   -375.854  mm,	Z =   -247.918  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[212]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.791  mm,	Y =   -375.879  mm,	Z =   -246.974  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[213]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.008  mm,	Y =   -375.678  mm,	Z =   -247.903  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[214]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.316  mm,	Y =   -375.508  mm,	Z =   -247.816  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[215]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.561  mm,	Y =   -375.361  mm,	Z =   -247.881  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[216]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.813  mm,	Y =   -375.228  mm,	Z =   -247.722  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[217]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.962  mm,	Y =   -375.206  mm,	Z =   -246.937  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[218]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.102  mm,	Y =   -375.054  mm,	Z =   -247.809  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[219]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.385  mm,	Y =   -374.894  mm,	Z =   -247.770  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[220]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.761  mm,	Y =   -374.736  mm,	Z =   -247.040  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[221]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.005  mm,	Y =   -374.597  mm,	Z =   -247.017  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[222]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.221  mm,	Y =   -374.403  mm,	Z =   -247.873  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[223]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.304  mm,	Y =   -374.429  mm,	Z =   -246.955  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[224]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.560  mm,	Y =   -374.277  mm,	Z =   -247.015  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[225]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.528  mm,	Y =   -374.229  mm,	Z =   -247.842  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[226]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.809  mm,	Y =   -374.065  mm,	Z =   -247.852  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[227]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.077  mm,	Y =   -373.974  mm,	Z =   -247.071  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[228]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.272  mm,	Y =   -373.794  mm,	Z =   -247.907  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[229]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.368  mm,	Y =   -373.798  mm,	Z =   -247.163  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[230]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.606  mm,	Y =   -373.605  mm,	Z =   -247.854  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[231]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.970  mm,	Y =   -373.469  mm,	Z =   -246.938  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[232]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.898  mm,	Y =   -373.437  mm,	Z =   -247.849  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[233]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.261  mm,	Y =   -373.296  mm,	Z =   -247.000  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[234]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.190  mm,	Y =   -373.264  mm,	Z =   -247.903  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[235]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.791  mm,	Y =   -372.983  mm,	Z =   -247.079  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[236]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.721  mm,	Y =   -372.958  mm,	Z =   -247.891  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[237]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.937  mm,	Y =   -372.835  mm,	Z =   -247.873  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[238]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.276  mm,	Y =   -372.640  mm,	Z =   -247.862  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[239]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.543  mm,	Y =   -372.483  mm,	Z =   -247.902  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[240]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.884  mm,	Y =   -372.349  mm,	Z =   -247.117  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[241]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  255.202  mm,	Y =   -372.175  mm,	Z =   -247.000  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[242]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  255.983  mm,	Y =   -371.724  mm,	Z =   -247.005  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[243]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.582  mm,	Y =   -371.374  mm,	Z =   -247.049  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[244]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.780  mm,	Y =   -371.190  mm,	Z =   -247.910  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[245]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.909  mm,	Y =   -371.189  mm,	Z =   -247.012  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[246]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  257.053  mm,	Y =   -371.039  mm,	Z =   -247.826  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[247]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  257.712  mm,	Y =   -370.721  mm,	Z =   -247.058  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[248]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.021  mm,	Y =   -370.553  mm,	Z =   -246.928  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[249]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.233  mm,	Y =   -370.420  mm,	Z =   -247.057  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[250]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.156  mm,	Y =   -370.396  mm,	Z =   -247.909  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[251]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.534  mm,	Y =   -370.255  mm,	Z =   -246.952  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[252]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.360  mm,	Y =   -369.767  mm,	Z =   -247.085  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[253]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.624  mm,	Y =   -369.626  mm,	Z =   -246.946  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[254]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.581  mm,	Y =   -369.580  mm,	Z =   -247.826  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[255]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.850  mm,	Y =   -369.433  mm,	Z =   -247.719  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[256]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.203  mm,	Y =   -369.285  mm,	Z =   -247.030  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[257]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.102  mm,	Y =   -369.276  mm,	Z =   -247.861  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[258]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.799  mm,	Y =   -368.948  mm,	Z =   -246.946  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[259]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.953  mm,	Y =   -368.787  mm,	Z =   -247.838  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[260]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.595  mm,	Y =   -368.489  mm,	Z =   -246.931  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[261]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.492  mm,	Y =   -368.484  mm,	Z =   -247.733  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[262]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.744  mm,	Y =   -368.315  mm,	Z =   -247.907  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[263]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  262.012  mm,	Y =   -368.168  mm,	Z =   -247.018  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[264]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  262.020  mm,	Y =   -367.946  mm,	Z =   -246.990  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[265]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.807  mm,	Y =   -367.809  mm,	Z =   -247.676  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[266]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.763  mm,	Y =   -367.766  mm,	Z =   -247.361  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[267]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.508  mm,	Y =   -367.628  mm,	Z =   -246.935  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[268]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.375  mm,	Y =   -364.385  mm,	Z =   -247.823  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[269]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.938  mm,	Y =   -363.868  mm,	Z =   -247.705  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[270]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.221  mm,	Y =   -363.573  mm,	Z =   -247.867  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[271]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.815  mm,	Y =   -362.968  mm,	Z =   -246.933  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[272]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.138  mm,	Y =   -362.507  mm,	Z =   -247.263  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[273]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.421  mm,	Y =   -361.901  mm,	Z =   -247.855  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[274]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.712  mm,	Y =   -361.477  mm,	Z =   -247.260  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[275]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.112  mm,	Y =   -360.396  mm,	Z =   -247.040  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[276]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.205  mm,	Y =   -358.703  mm,	Z =   -247.709  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[277]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.271  mm,	Y =   -358.634  mm,	Z =   -246.942  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[278]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.160  mm,	Y =   -358.215  mm,	Z =   -247.800  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[279]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.134  mm,	Y =   -357.790  mm,	Z =   -246.976  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[280]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.564  mm,	Y =   -356.345  mm,	Z =   -246.974  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[281]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.176  mm,	Y =   -355.792  mm,	Z =   -247.887  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[282]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.836  mm,	Y =   -355.192  mm,	Z =   -247.804  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[283]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.508  mm,	Y =   -354.503  mm,	Z =   -246.932  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[284]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.142  mm,	Y =   -353.877  mm,	Z =   -246.992  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[285]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.841  mm,	Y =   -353.356  mm,	Z =   -246.993  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[286]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.742  mm,	Y =   -353.302  mm,	Z =   -247.835  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[287]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.443  mm,	Y =   -352.673  mm,	Z =   -247.038  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[288]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.044  mm,	Y =   -352.096  mm,	Z =   -247.851  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[289]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  288.675  mm,	Y =   -351.332  mm,	Z =   -246.964  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[290]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  288.353  mm,	Y =   -350.769  mm,	Z =   -246.929  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[291]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.937  mm,	Y =   -350.173  mm,	Z =   -247.821  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[292]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.298  mm,	Y =   -348.946  mm,	Z =   -246.956  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[293]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.236  mm,	Y =   -348.969  mm,	Z =   -247.890  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[294]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.881  mm,	Y =   -348.338  mm,	Z =   -247.779  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[295]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.511  mm,	Y =   -347.707  mm,	Z =   -247.846  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[296]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.136  mm,	Y =   -347.064  mm,	Z =   -247.894  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[297]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.796  mm,	Y =   -346.475  mm,	Z =   -247.882  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[298]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.149  mm,	Y =   -345.231  mm,	Z =   -247.005  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[299]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  284.729  mm,	Y =   -344.626  mm,	Z =   -247.883  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[300]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  284.338  mm,	Y =   -343.951  mm,	Z =   -247.902  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[301]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  284.050  mm,	Y =   -343.438  mm,	Z =   -247.790  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[302]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  283.689  mm,	Y =   -342.704  mm,	Z =   -247.019  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[303]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.988  mm,	Y =   -341.478  mm,	Z =   -246.929  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[304]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.632  mm,	Y =   -340.877  mm,	Z =   -247.044  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[305]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.534  mm,	Y =   -340.818  mm,	Z =   -247.831  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[306]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.229  mm,	Y =   -340.163  mm,	Z =   -246.927  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[307]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.857  mm,	Y =   -339.656  mm,	Z =   -247.915  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[308]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.572  mm,	Y =   -339.038  mm,	Z =   -247.021  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[309]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.209  mm,	Y =   -338.428  mm,	Z =   -247.162  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[310]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  280.827  mm,	Y =   -337.736  mm,	Z =   -246.940  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[311]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  280.733  mm,	Y =   -337.705  mm,	Z =   -247.874  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[312]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  280.376  mm,	Y =   -337.092  mm,	Z =   -247.916  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[313]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  280.096  mm,	Y =   -336.474  mm,	Z =   -246.967  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[314]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  279.313  mm,	Y =   -335.232  mm,	Z =   -247.773  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[315]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  278.582  mm,	Y =   -333.969  mm,	Z =   -247.808  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[316]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  278.233  mm,	Y =   -333.363  mm,	Z =   -247.787  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[317]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  277.816  mm,	Y =   -332.657  mm,	Z =   -247.906  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[318]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  277.501  mm,	Y =   -332.130  mm,	Z =   -247.894  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[319]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  277.107  mm,	Y =   -331.460  mm,	Z =   -247.029  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[320]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  276.586  mm,	Y =   -331.005  mm,	Z =   -247.851  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[321]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  276.203  mm,	Y =   -330.644  mm,	Z =   -247.800  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[322]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  275.923  mm,	Y =   -330.481  mm,	Z =   -247.911  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[323]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  275.859  mm,	Y =   -330.368  mm,	Z =   -247.197  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[324]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  275.439  mm,	Y =   -330.089  mm,	Z =   -246.952  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[325]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  275.290  mm,	Y =   -330.105  mm,	Z =   -247.843  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[326]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  274.871  mm,	Y =   -329.928  mm,	Z =   -247.794  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[327]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  274.430  mm,	Y =   -329.682  mm,	Z =   -246.939  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[328]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  272.663  mm,	Y =   -329.507  mm,	Z =   -247.771  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[329]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  272.602  mm,	Y =   -329.435  mm,	Z =   -246.926  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[330]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  272.026  mm,	Y =   -329.442  mm,	Z =   -247.025  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[331]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  271.577  mm,	Y =   -329.572  mm,	Z =   -247.894  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[332]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  270.816  mm,	Y =   -329.670  mm,	Z =   -247.755  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[333]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  270.172  mm,	Y =   -329.786  mm,	Z =   -246.926  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[334]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  269.509  mm,	Y =   -330.064  mm,	Z =   -247.803  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[335]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.819  mm,	Y =   -352.140  mm,	Z =   -247.429  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[336]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.734  mm,	Y =   -352.065  mm,	Z =   -247.788  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[337]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.621  mm,	Y =   -351.837  mm,	Z =   -246.941  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[338]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.367  mm,	Y =   -351.908  mm,	Z =   -246.948  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[339]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.066  mm,	Y =   -352.146  mm,	Z =   -247.810  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[340]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.785  mm,	Y =   -352.304  mm,	Z =   -247.758  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[341]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.825  mm,	Y =   -352.218  mm,	Z =   -246.976  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[342]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.527  mm,	Y =   -352.459  mm,	Z =   -247.832  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[343]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.249  mm,	Y =   -352.625  mm,	Z =   -247.897  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[344]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.302  mm,	Y =   -352.516  mm,	Z =   -246.925  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[345]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.944  mm,	Y =   -352.794  mm,	Z =   -247.806  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[346]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.160  mm,	Y =   -353.189  mm,	Z =   -247.095  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[347]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.852  mm,	Y =   -353.424  mm,	Z =   -247.810  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[348]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.311  mm,	Y =   -353.743  mm,	Z =   -247.891  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[349]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.336  mm,	Y =   -353.653  mm,	Z =   -246.954  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[350]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.014  mm,	Y =   -353.917  mm,	Z =   -247.914  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[351]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.758  mm,	Y =   -354.064  mm,	Z =   -247.902  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[352]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.482  mm,	Y =   -354.223  mm,	Z =   -247.907  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[353]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.456  mm,	Y =   -354.164  mm,	Z =   -246.994  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[354]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.249  mm,	Y =   -354.287  mm,	Z =   -247.033  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[355]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.196  mm,	Y =   -354.386  mm,	Z =   -247.880  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[356]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.899  mm,	Y =   -354.552  mm,	Z =   -247.807  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[357]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.651  mm,	Y =   -354.696  mm,	Z =   -247.819  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[358]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.399  mm,	Y =   -354.782  mm,	Z =   -247.078  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[359]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.067  mm,	Y =   -355.035  mm,	Z =   -247.850  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[360]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.808  mm,	Y =   -355.118  mm,	Z =   -247.015  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[361]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.227  mm,	Y =   -355.526  mm,	Z =   -247.909  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[362]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.263  mm,	Y =   -355.435  mm,	Z =   -247.055  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[363]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.964  mm,	Y =   -355.610  mm,	Z =   -247.072  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[364]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.663  mm,	Y =   -355.851  mm,	Z =   -247.905  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[365]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.445  mm,	Y =   -355.978  mm,	Z =   -247.920  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[366]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.862  mm,	Y =   -356.305  mm,	Z =   -247.800  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[367]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.591  mm,	Y =   -356.405  mm,	Z =   -247.104  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[368]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.320  mm,	Y =   -356.559  mm,	Z =   -247.067  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[369]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.015  mm,	Y =   -356.727  mm,	Z =   -246.977  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[370]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.768  mm,	Y =   -356.870  mm,	Z =   -246.984  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[371]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.471  mm,	Y =   -357.037  mm,	Z =   -246.926  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[372]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.171  mm,	Y =   -357.283  mm,	Z =   -247.824  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[373]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.916  mm,	Y =   -357.363  mm,	Z =   -246.992  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[374]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.880  mm,	Y =   -357.458  mm,	Z =   -247.901  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[375]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.048  mm,	Y =   -357.866  mm,	Z =   -247.017  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[376]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.810  mm,	Y =   -358.007  mm,	Z =   -247.054  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[377]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.515  mm,	Y =   -358.240  mm,	Z =   -247.832  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[378]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.224  mm,	Y =   -358.338  mm,	Z =   -246.962  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[379]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.946  mm,	Y =   -358.573  mm,	Z =   -247.893  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[380]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.667  mm,	Y =   -358.659  mm,	Z =   -246.964  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[381]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.436  mm,	Y =   -358.867  mm,	Z =   -247.874  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[382]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.168  mm,	Y =   -359.019  mm,	Z =   -247.852  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[383]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.088  mm,	Y =   -358.994  mm,	Z =   -246.956  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[384]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.338  mm,	Y =   -359.499  mm,	Z =   -247.859  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[385]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.021  mm,	Y =   -359.683  mm,	Z =   -247.871  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[386]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.983  mm,	Y =   -359.639  mm,	Z =   -247.053  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[387]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.471  mm,	Y =   -360.001  mm,	Z =   -247.886  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[388]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.460  mm,	Y =   -359.937  mm,	Z =   -247.008  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[389]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.188  mm,	Y =   -360.161  mm,	Z =   -247.834  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[390]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.639  mm,	Y =   -360.412  mm,	Z =   -247.022  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[391]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.359  mm,	Y =   -360.579  mm,	Z =   -247.082  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[392]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.113  mm,	Y =   -360.782  mm,	Z =   -247.837  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[393]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.281  mm,	Y =   -361.266  mm,	Z =   -247.891  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[394]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.253  mm,	Y =   -361.209  mm,	Z =   -246.975  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[395]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.670  mm,	Y =   -361.621  mm,	Z =   -247.913  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[396]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.399  mm,	Y =   -361.776  mm,	Z =   -247.895  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[397]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.392  mm,	Y =   -360.505  mm,	Z =   -224.946  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[398]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.357  mm,	Y =   -360.593  mm,	Z =   -225.785  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[399]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.000  mm,	Y =   -360.802  mm,	Z =   -225.822  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[400]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.702  mm,	Y =   -360.970  mm,	Z =   -225.770  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[401]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.487  mm,	Y =   -361.098  mm,	Z =   -225.822  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[402]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.404  mm,	Y =   -361.075  mm,	Z =   -224.940  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[403]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.811  mm,	Y =   -361.483  mm,	Z =   -225.762  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[404]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.580  mm,	Y =   -361.587  mm,	Z =   -225.392  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[405]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.529  mm,	Y =   -361.658  mm,	Z =   -225.909  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[406]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.294  mm,	Y =   -361.754  mm,	Z =   -225.413  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[407]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.210  mm,	Y =   -361.841  mm,	Z =   -225.896  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[408]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.623  mm,	Y =   -362.182  mm,	Z =   -225.911  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[409]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.557  mm,	Y =   -362.142  mm,	Z =   -224.952  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[410]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.491  mm,	Y =   -362.215  mm,	Z =   -225.396  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[411]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.269  mm,	Y =   -362.315  mm,	Z =   -225.031  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[412]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.297  mm,	Y =   -362.369  mm,	Z =   -225.901  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[413]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.990  mm,	Y =   -362.547  mm,	Z =   -225.923  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[414]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.655  mm,	Y =   -362.675  mm,	Z =   -225.107  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[415]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.373  mm,	Y =   -362.893  mm,	Z =   -225.776  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[416]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.910  mm,	Y =   -363.127  mm,	Z =   -225.378  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[417]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.140  mm,	Y =   -363.606  mm,	Z =   -225.794  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[418]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.874  mm,	Y =   -363.726  mm,	Z =   -225.370  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[419]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.845  mm,	Y =   -363.780  mm,	Z =   -225.848  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[420]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.859  mm,	Y =   -364.284  mm,	Z =   -225.040  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[421]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.784  mm,	Y =   -364.357  mm,	Z =   -225.398  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[422]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.246  mm,	Y =   -364.630  mm,	Z =   -224.931  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[423]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.248  mm,	Y =   -364.668  mm,	Z =   -225.413  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[424]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.957  mm,	Y =   -364.870  mm,	Z =   -225.849  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[425]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.306  mm,	Y =   -365.173  mm,	Z =   -224.949  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[426]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.123  mm,	Y =   -365.346  mm,	Z =   -225.786  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[427]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.718  mm,	Y =   -365.520  mm,	Z =   -225.031  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[428]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.480  mm,	Y =   -365.726  mm,	Z =   -225.890  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[429]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.376  mm,	Y =   -365.713  mm,	Z =   -224.981  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[430]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.172  mm,	Y =   -365.903  mm,	Z =   -225.869  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[431]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  224.799  mm,	Y =   -366.046  mm,	Z =   -224.974  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[432]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  224.881  mm,	Y =   -366.070  mm,	Z =   -225.869  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[433]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  224.484  mm,	Y =   -366.225  mm,	Z =   -224.935  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[434]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.897  mm,	Y =   -366.567  mm,	Z =   -224.985  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[435]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.958  mm,	Y =   -366.608  mm,	Z =   -225.921  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[436]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.659  mm,	Y =   -366.774  mm,	Z =   -225.845  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[437]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  223.279  mm,	Y =   -366.933  mm,	Z =   -225.088  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[438]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.812  mm,	Y =   -367.228  mm,	Z =   -225.404  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[439]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.634  mm,	Y =   -367.307  mm,	Z =   -225.106  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[440]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.336  mm,	Y =   -367.475  mm,	Z =   -225.055  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[441]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.421  mm,	Y =   -367.495  mm,	Z =   -225.924  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[442]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.156  mm,	Y =   -367.606  mm,	Z =   -225.402  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[443]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  222.101  mm,	Y =   -367.678  mm,	Z =   -225.899  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[444]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.716  mm,	Y =   -367.828  mm,	Z =   -224.998  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[445]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.807  mm,	Y =   -367.841  mm,	Z =   -225.809  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[446]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.506  mm,	Y =   -368.013  mm,	Z =   -225.782  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[447]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  221.122  mm,	Y =   -368.170  mm,	Z =   -224.979  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[448]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  220.843  mm,	Y =   -368.401  mm,	Z =   -225.860  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[449]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  220.507  mm,	Y =   -368.525  mm,	Z =   -224.981  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[450]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  220.223  mm,	Y =   -368.756  mm,	Z =   -225.819  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[451]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.902  mm,	Y =   -368.872  mm,	Z =   -224.956  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[452]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.585  mm,	Y =   -369.089  mm,	Z =   -225.369  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[453]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.644  mm,	Y =   -369.097  mm,	Z =   -225.904  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[454]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  219.320  mm,	Y =   -369.278  mm,	Z =   -225.830  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[455]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.586  mm,	Y =   -369.630  mm,	Z =   -224.926  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[456]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  218.442  mm,	Y =   -369.788  mm,	Z =   -225.856  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[457]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.955  mm,	Y =   -370.032  mm,	Z =   -225.398  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[458]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.837  mm,	Y =   -370.100  mm,	Z =   -225.400  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[459]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.794  mm,	Y =   -370.161  mm,	Z =   -225.844  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[460]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.511  mm,	Y =   -370.286  mm,	Z =   -225.369  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[461]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.487  mm,	Y =   -370.338  mm,	Z =   -225.839  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[462]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  217.210  mm,	Y =   -370.501  mm,	Z =   -225.878  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[463]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  216.778  mm,	Y =   -370.682  mm,	Z =   -225.031  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[464]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  216.880  mm,	Y =   -370.686  mm,	Z =   -225.816  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[465]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  216.154  mm,	Y =   -371.071  mm,	Z =   -225.383  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[466]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.904  mm,	Y =   -371.214  mm,	Z =   -225.372  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[467]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.958  mm,	Y =   -371.227  mm,	Z =   -225.918  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[468]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.665  mm,	Y =   -371.387  mm,	Z =   -225.804  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[469]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.331  mm,	Y =   -371.586  mm,	Z =   -225.886  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[470]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.026  mm,	Y =   -371.742  mm,	Z =   -225.177  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[471]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.096  mm,	Y =   -371.773  mm,	Z =   -225.898  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[472]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.157  mm,	Y =   -372.393  mm,	Z =   -224.958  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[473]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.297  mm,	Y =   -372.394  mm,	Z =   -225.902  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[474]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.529  mm,	Y =   -372.532  mm,	Z =   -225.806  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[475]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  215.945  mm,	Y =   -372.668  mm,	Z =   -225.782  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[476]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.636  mm,	Y =   -376.299  mm,	Z =   -225.905  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[477]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.516  mm,	Y =   -376.334  mm,	Z =   -225.076  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[478]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.272  mm,	Y =   -378.286  mm,	Z =   -224.926  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[479]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.053  mm,	Y =   -379.156  mm,	Z =   -225.859  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[480]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  185.851  mm,	Y =   -379.926  mm,	Z =   -225.382  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[481]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  185.800  mm,	Y =   -380.295  mm,	Z =   -225.483  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[482]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  185.847  mm,	Y =   -380.797  mm,	Z =   -225.872  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[483]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  185.769  mm,	Y =   -380.859  mm,	Z =   -224.974  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[484]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  185.896  mm,	Y =   -381.491  mm,	Z =   -225.879  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[485]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.008  mm,	Y =   -382.255  mm,	Z =   -225.033  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[486]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.228  mm,	Y =   -382.820  mm,	Z =   -224.959  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[487]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.619  mm,	Y =   -383.588  mm,	Z =   -225.001  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[488]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  186.703  mm,	Y =   -383.610  mm,	Z =   -225.898  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[489]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.014  mm,	Y =   -384.264  mm,	Z =   -225.061  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[490]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.375  mm,	Y =   -384.782  mm,	Z =   -225.838  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[491]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  187.642  mm,	Y =   -385.308  mm,	Z =   -225.374  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[492]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.498  mm,	Y =   -386.785  mm,	Z =   -225.413  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[493]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.473  mm,	Y =   -386.803  mm,	Z =   -224.982  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[494]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  188.877  mm,	Y =   -387.392  mm,	Z =   -225.780  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[495]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  189.626  mm,	Y =   -388.676  mm,	Z =   -225.866  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[496]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.032  mm,	Y =   -389.448  mm,	Z =   -225.376  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[497]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  190.306  mm,	Y =   -389.869  mm,	Z =   -225.756  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[498]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  191.062  mm,	Y =   -391.232  mm,	Z =   -225.376  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[499]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  191.772  mm,	Y =   -392.386  mm,	Z =   -225.912  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[500]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  191.716  mm,	Y =   -392.426  mm,	Z =   -224.935  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[501]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  192.126  mm,	Y =   -393.072  mm,	Z =   -225.383  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[502]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  192.449  mm,	Y =   -393.561  mm,	Z =   -225.890  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[503]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  192.468  mm,	Y =   -393.712  mm,	Z =   -225.051  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[504]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  193.110  mm,	Y =   -394.836  mm,	Z =   -224.967  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[505]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  193.212  mm,	Y =   -394.888  mm,	Z =   -225.862  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[506]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  193.527  mm,	Y =   -395.560  mm,	Z =   -224.953  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[507]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.305  mm,	Y =   -396.776  mm,	Z =   -225.891  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[508]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.425  mm,	Y =   -397.052  mm,	Z =   -225.405  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[509]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.620  mm,	Y =   -397.452  mm,	Z =   -224.964  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[510]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.695  mm,	Y =   -397.452  mm,	Z =   -225.885  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[511]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  194.972  mm,	Y =   -398.059  mm,	Z =   -224.972  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[512]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  195.239  mm,	Y =   -398.464  mm,	Z =   -225.395  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[513]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  195.836  mm,	Y =   -399.432  mm,	Z =   -225.860  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[514]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  195.979  mm,	Y =   -399.749  mm,	Z =   -225.363  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[515]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.097  mm,	Y =   -400.011  mm,	Z =   -224.947  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[516]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.178  mm,	Y =   -400.041  mm,	Z =   -225.740  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[517]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.456  mm,	Y =   -400.527  mm,	Z =   -225.708  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[518]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  196.993  mm,	Y =   -401.498  mm,	Z =   -225.413  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[519]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.525  mm,	Y =   -402.479  mm,	Z =   -225.000  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[520]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.618  mm,	Y =   -402.582  mm,	Z =   -225.399  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[521]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  197.819  mm,	Y =   -402.997  mm,	Z =   -224.930  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[522]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  198.007  mm,	Y =   -403.202  mm,	Z =   -225.792  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[523]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  198.357  mm,	Y =   -403.809  mm,	Z =   -225.778  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[524]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  198.596  mm,	Y =   -404.332  mm,	Z =   -225.007  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[525]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  198.663  mm,	Y =   -404.328  mm,	Z =   -225.859  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[526]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.022  mm,	Y =   -405.057  mm,	Z =   -225.090  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[527]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.160  mm,	Y =   -405.255  mm,	Z =   -225.389  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[528]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.411  mm,	Y =   -405.618  mm,	Z =   -225.906  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[529]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  199.783  mm,	Y =   -406.278  mm,	Z =   -225.793  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[530]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.163  mm,	Y =   -406.994  mm,	Z =   -225.381  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[531]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.461  mm,	Y =   -407.455  mm,	Z =   -225.770  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[532]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.460  mm,	Y =   -407.564  mm,	Z =   -224.979  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[533]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.697  mm,	Y =   -407.920  mm,	Z =   -225.364  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[534]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  200.853  mm,	Y =   -408.124  mm,	Z =   -225.829  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[535]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.213  mm,	Y =   -408.809  mm,	Z =   -225.405  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[536]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.559  mm,	Y =   -409.349  mm,	Z =   -225.819  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[537]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.861  mm,	Y =   -409.821  mm,	Z =   -225.925  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[538]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  201.962  mm,	Y =   -410.061  mm,	Z =   -225.152  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[539]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  202.367  mm,	Y =   -410.521  mm,	Z =   -225.735  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[540]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.004  mm,	Y =   -411.840  mm,	Z =   -224.989  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[541]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.055  mm,	Y =   -411.791  mm,	Z =   -225.781  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[542]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  204.385  mm,	Y =   -411.907  mm,	Z =   -225.877  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[543]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  205.041  mm,	Y =   -412.216  mm,	Z =   -224.940  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[544]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  206.124  mm,	Y =   -412.327  mm,	Z =   -225.830  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[545]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  207.318  mm,	Y =   -412.345  mm,	Z =   -225.752  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[546]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  208.519  mm,	Y =   -412.173  mm,	Z =   -225.881  mm,
	W =  179.765 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[547]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.635  mm,	Y =   -389.642  mm,	Z =   -225.857  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[548]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.559  mm,	Y =   -389.777  mm,	Z =   -224.931  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[549]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.510  mm,	Y =   -390.047  mm,	Z =   -224.972  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[550]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.570  mm,	Y =   -389.966  mm,	Z =   -225.847  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[551]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.575  mm,	Y =   -390.248  mm,	Z =   -225.872  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[552]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.642  mm,	Y =   -390.596  mm,	Z =   -225.749  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[553]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.582  mm,	Y =   -390.691  mm,	Z =   -224.931  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[554]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.755  mm,	Y =   -390.830  mm,	Z =   -224.945  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[555]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.923  mm,	Y =   -390.794  mm,	Z =   -225.041  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[556]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.292  mm,	Y =   -390.574  mm,	Z =   -225.872  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[557]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.262  mm,	Y =   -390.660  mm,	Z =   -225.010  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[558]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.648  mm,	Y =   -390.366  mm,	Z =   -225.894  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[559]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.828  mm,	Y =   -390.309  mm,	Z =   -225.316  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[560]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  226.929  mm,	Y =   -390.214  mm,	Z =   -225.768  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[561]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.204  mm,	Y =   -390.088  mm,	Z =   -225.365  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[562]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.444  mm,	Y =   -389.982  mm,	Z =   -224.962  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[563]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  227.842  mm,	Y =   -389.684  mm,	Z =   -225.808  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[564]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.143  mm,	Y =   -389.577  mm,	Z =   -224.984  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[565]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.461  mm,	Y =   -389.397  mm,	Z =   -224.932  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[566]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.760  mm,	Y =   -389.151  mm,	Z =   -225.837  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[567]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  228.969  mm,	Y =   -389.072  mm,	Z =   -225.339  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[568]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.080  mm,	Y =   -388.961  mm,	Z =   -225.908  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[569]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.313  mm,	Y =   -388.891  mm,	Z =   -225.105  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[570]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.431  mm,	Y =   -388.802  mm,	Z =   -225.358  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[571]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  229.961  mm,	Y =   -388.530  mm,	Z =   -224.942  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[572]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.290  mm,	Y =   -388.273  mm,	Z =   -225.777  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[573]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.262  mm,	Y =   -388.357  mm,	Z =   -224.933  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[574]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  230.551  mm,	Y =   -388.189  mm,	Z =   -224.941  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[575]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.221  mm,	Y =   -387.730  mm,	Z =   -225.842  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[576]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.524  mm,	Y =   -387.596  mm,	Z =   -225.339  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[577]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.779  mm,	Y =   -387.448  mm,	Z =   -225.341  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[578]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  231.886  mm,	Y =   -387.348  mm,	Z =   -225.817  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[579]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.411  mm,	Y =   -387.115  mm,	Z =   -224.944  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[580]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  232.704  mm,	Y =   -386.873  mm,	Z =   -225.847  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[581]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.070  mm,	Y =   -386.661  mm,	Z =   -225.857  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[582]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.354  mm,	Y =   -386.571  mm,	Z =   -224.940  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[583]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  233.702  mm,	Y =   -386.334  mm,	Z =   -225.387  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[584]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.018  mm,	Y =   -386.113  mm,	Z =   -225.871  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[585]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.251  mm,	Y =   -386.052  mm,	Z =   -224.950  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[586]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.584  mm,	Y =   -385.784  mm,	Z =   -225.892  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[587]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.750  mm,	Y =   -385.728  mm,	Z =   -225.408  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[588]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.222  mm,	Y =   -385.416  mm,	Z =   -225.883  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[589]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.479  mm,	Y =   -385.268  mm,	Z =   -225.881  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[590]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.764  mm,	Y =   -385.148  mm,	Z =   -225.328  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[591]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.805  mm,	Y =   -385.077  mm,	Z =   -225.922  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[592]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.079  mm,	Y =   -384.959  mm,	Z =   -225.416  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[593]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.439  mm,	Y =   -384.715  mm,	Z =   -225.869  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[594]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.695  mm,	Y =   -384.606  mm,	Z =   -225.387  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[595]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.741  mm,	Y =   -384.611  mm,	Z =   -225.000  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[596]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.093  mm,	Y =   -384.411  mm,	Z =   -224.955  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[597]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.353  mm,	Y =   -384.259  mm,	Z =   -224.978  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[598]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.648  mm,	Y =   -384.054  mm,	Z =   -225.411  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[599]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.669  mm,	Y =   -384.009  mm,	Z =   -225.820  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[600]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.972  mm,	Y =   -383.831  mm,	Z =   -225.856  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[601]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.234  mm,	Y =   -383.720  mm,	Z =   -225.344  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[602]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.600  mm,	Y =   -383.464  mm,	Z =   -225.913  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[603]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.858  mm,	Y =   -383.337  mm,	Z =   -225.637  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[604]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.286  mm,	Y =   -383.111  mm,	Z =   -225.378  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[605]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.396  mm,	Y =   -383.048  mm,	Z =   -225.375  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[606]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.483  mm,	Y =   -383.023  mm,	Z =   -225.059  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[607]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.820  mm,	Y =   -382.762  mm,	Z =   -225.882  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[608]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.385  mm,	Y =   -382.440  mm,	Z =   -225.833  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[609]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.466  mm,	Y =   -382.464  mm,	Z =   -224.948  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[610]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.667  mm,	Y =   -382.310  mm,	Z =   -225.415  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[611]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.011  mm,	Y =   -382.080  mm,	Z =   -225.816  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[612]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.057  mm,	Y =   -382.114  mm,	Z =   -225.054  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[613]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.651  mm,	Y =   -381.705  mm,	Z =   -225.880  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[614]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.657  mm,	Y =   -381.744  mm,	Z =   -225.353  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[615]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.682  mm,	Y =   -381.762  mm,	Z =   -224.954  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[616]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.916  mm,	Y =   -381.590  mm,	Z =   -225.405  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[617]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.020  mm,	Y =   -381.568  mm,	Z =   -224.939  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[618]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.136  mm,	Y =   -381.466  mm,	Z =   -225.368  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[619]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.299  mm,	Y =   -381.335  mm,	Z =   -225.829  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[620]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.862  mm,	Y =   -381.010  mm,	Z =   -225.826  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[621]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.967  mm,	Y =   -380.988  mm,	Z =   -225.344  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[622]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.191  mm,	Y =   -380.884  mm,	Z =   -225.033  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[623]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.329  mm,	Y =   -380.773  mm,	Z =   -225.413  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[624]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.446  mm,	Y =   -380.710  mm,	Z =   -225.365  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[625]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.789  mm,	Y =   -380.472  mm,	Z =   -225.855  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[626]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.833  mm,	Y =   -380.489  mm,	Z =   -225.337  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[627]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.997  mm,	Y =   -380.389  mm,	Z =   -225.404  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[628]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.143  mm,	Y =   -380.341  mm,	Z =   -224.949  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[629]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.128  mm,	Y =   -380.271  mm,	Z =   -225.924  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[630]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.422  mm,	Y =   -380.111  mm,	Z =   -225.802  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[631]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.455  mm,	Y =   -380.163  mm,	Z =   -224.926  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[632]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.451  mm,	Y =   -380.132  mm,	Z =   -225.328  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[633]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.272  mm,	Y =   -379.659  mm,	Z =   -225.320  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[634]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.523  mm,	Y =   -379.514  mm,	Z =   -225.322  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[635]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.626  mm,	Y =   -379.406  mm,	Z =   -225.922  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[636]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.945  mm,	Y =   -379.226  mm,	Z =   -225.871  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[637]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.321  mm,	Y =   -379.048  mm,	Z =   -225.388  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[638]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.436  mm,	Y =   -378.982  mm,	Z =   -225.386  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[639]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.616  mm,	Y =   -378.914  mm,	Z =   -224.933  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[640]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.813  mm,	Y =   -378.762  mm,	Z =   -225.399  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[641]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.228  mm,	Y =   -378.561  mm,	Z =   -224.929  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[642]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.322  mm,	Y =   -378.470  mm,	Z =   -225.390  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[643]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.499  mm,	Y =   -378.335  mm,	Z =   -225.793  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[644]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.760  mm,	Y =   -378.218  mm,	Z =   -225.374  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[645]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.085  mm,	Y =   -377.995  mm,	Z =   -225.818  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[646]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.384  mm,	Y =   -377.816  mm,	Z =   -225.894  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[647]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.435  mm,	Y =   -377.829  mm,	Z =   -225.369  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[648]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.720  mm,	Y =   -377.698  mm,	Z =   -224.950  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[649]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.727  mm,	Y =   -377.624  mm,	Z =   -225.823  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[650]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.026  mm,	Y =   -377.491  mm,	Z =   -225.335  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[651]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.355  mm,	Y =   -377.320  mm,	Z =   -225.096  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[652]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.339  mm,	Y =   -377.274  mm,	Z =   -225.774  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[653]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.677  mm,	Y =   -377.068  mm,	Z =   -225.918  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[654]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.867  mm,	Y =   -376.998  mm,	Z =   -225.416  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[655]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.198  mm,	Y =   -376.775  mm,	Z =   -225.823  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[656]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.359  mm,	Y =   -376.750  mm,	Z =   -224.979  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[657]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.512  mm,	Y =   -376.587  mm,	Z =   -225.904  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[658]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.662  mm,	Y =   -376.546  mm,	Z =   -225.329  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[659]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.870  mm,	Y =   -376.383  mm,	Z =   -225.871  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[660]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.161  mm,	Y =   -376.220  mm,	Z =   -225.811  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[661]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.431  mm,	Y =   -376.071  mm,	Z =   -225.717  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[662]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.510  mm,	Y =   -376.086  mm,	Z =   -224.963  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[663]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.835  mm,	Y =   -375.866  mm,	Z =   -225.367  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[664]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.144  mm,	Y =   -375.724  mm,	Z =   -224.927  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[665]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.539  mm,	Y =   -375.459  mm,	Z =   -225.370  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[666]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.711  mm,	Y =   -375.322  mm,	Z =   -225.842  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[667]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.790  mm,	Y =   -375.348  mm,	Z =   -224.952  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[668]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.956  mm,	Y =   -375.174  mm,	Z =   -225.925  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[669]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.157  mm,	Y =   -375.102  mm,	Z =   -225.380  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[670]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.518  mm,	Y =   -374.896  mm,	Z =   -225.344  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[671]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.647  mm,	Y =   -374.782  mm,	Z =   -225.836  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[672]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.928  mm,	Y =   -374.617  mm,	Z =   -225.872  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[673]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.618  mm,	Y =   -374.291  mm,	Z =   -224.970  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[674]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.548  mm,	Y =   -374.258  mm,	Z =   -225.877  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[675]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.833  mm,	Y =   -374.101  mm,	Z =   -225.784  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[676]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.916  mm,	Y =   -374.117  mm,	Z =   -225.006  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[677]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  255.082  mm,	Y =   -373.949  mm,	Z =   -225.895  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[678]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  255.212  mm,	Y =   -373.949  mm,	Z =   -224.954  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[679]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  255.782  mm,	Y =   -373.545  mm,	Z =   -225.881  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[680]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  255.863  mm,	Y =   -373.538  mm,	Z =   -225.385  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[681]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.059  mm,	Y =   -373.389  mm,	Z =   -225.836  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[682]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.360  mm,	Y =   -373.216  mm,	Z =   -225.825  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[683]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.646  mm,	Y =   -373.087  mm,	Z =   -225.373  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[684]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  256.948  mm,	Y =   -372.876  mm,	Z =   -225.832  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[685]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  257.292  mm,	Y =   -372.671  mm,	Z =   -225.911  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[686]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  257.580  mm,	Y =   -372.508  mm,	Z =   -225.875  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[687]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  257.861  mm,	Y =   -372.347  mm,	Z =   -225.855  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[688]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.196  mm,	Y =   -372.156  mm,	Z =   -225.826  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[689]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.609  mm,	Y =   -371.982  mm,	Z =   -225.024  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[690]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.806  mm,	Y =   -371.808  mm,	Z =   -225.779  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[691]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  258.952  mm,	Y =   -371.791  mm,	Z =   -224.939  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[692]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.383  mm,	Y =   -371.465  mm,	Z =   -225.892  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[693]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  259.469  mm,	Y =   -371.460  mm,	Z =   -225.342  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[694]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.230  mm,	Y =   -371.016  mm,	Z =   -225.405  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[695]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.543  mm,	Y =   -370.834  mm,	Z =   -225.415  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[696]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  260.754  mm,	Y =   -370.719  mm,	Z =   -225.329  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[697]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.051  mm,	Y =   -370.577  mm,	Z =   -224.965  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[698]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.265  mm,	Y =   -370.381  mm,	Z =   -225.867  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[699]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.708  mm,	Y =   -370.199  mm,	Z =   -224.954  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[700]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.608  mm,	Y =   -370.187  mm,	Z =   -225.816  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[701]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.992  mm,	Y =   -370.036  mm,	Z =   -224.936  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[702]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.887  mm,	Y =   -370.021  mm,	Z =   -225.874  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[703]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  261.957  mm,	Y =   -370.021  mm,	Z =   -225.372  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[704]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  262.562  mm,	Y =   -369.706  mm,	Z =   -224.952  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[705]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  262.651  mm,	Y =   -369.621  mm,	Z =   -225.357  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[706]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  262.831  mm,	Y =   -369.521  mm,	Z =   -225.316  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[707]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  262.835  mm,	Y =   -369.473  mm,	Z =   -225.883  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[708]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  263.208  mm,	Y =   -369.299  mm,	Z =   -225.372  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[709]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  263.405  mm,	Y =   -369.148  mm,	Z =   -225.827  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[710]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  263.510  mm,	Y =   -369.129  mm,	Z =   -225.317  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[711]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  263.762  mm,	Y =   -368.977  mm,	Z =   -225.384  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[712]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.099  mm,	Y =   -368.820  mm,	Z =   -224.929  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[713]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.374  mm,	Y =   -368.623  mm,	Z =   -225.404  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[714]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.738  mm,	Y =   -368.449  mm,	Z =   -224.967  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[715]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  265.046  mm,	Y =   -368.215  mm,	Z =   -224.961  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[716]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.922  mm,	Y =   -368.223  mm,	Z =   -225.798  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[717]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  265.043  mm,	Y =   -368.011  mm,	Z =   -225.859  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[718]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  265.129  mm,	Y =   -367.854  mm,	Z =   -224.929  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[719]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.965  mm,	Y =   -367.806  mm,	Z =   -225.878  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[720]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.906  mm,	Y =   -367.646  mm,	Z =   -224.950  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[721]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.703  mm,	Y =   -367.604  mm,	Z =   -225.881  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[722]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.534  mm,	Y =   -367.499  mm,	Z =   -225.835  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[723]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  264.133  mm,	Y =   -367.358  mm,	Z =   -225.818  mm,
	W =  90.000 deg,	P =   89.765 deg,	R =   30.000 deg
};
P[724]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  293.100  mm,	Y =   -362.853  mm,	Z =   -224.936  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[725]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  293.358  mm,	Y =   -362.330  mm,	Z =   -225.599  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[726]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  293.664  mm,	Y =   -361.839  mm,	Z =   -225.016  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[727]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  293.942  mm,	Y =   -360.846  mm,	Z =   -225.924  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[728]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  294.171  mm,	Y =   -360.115  mm,	Z =   -225.066  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[729]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  294.153  mm,	Y =   -359.239  mm,	Z =   -225.885  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[730]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  293.722  mm,	Y =   -357.104  mm,	Z =   -225.135  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[731]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  293.309  mm,	Y =   -356.401  mm,	Z =   -225.818  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[732]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  293.138  mm,	Y =   -356.040  mm,	Z =   -225.356  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[733]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.629  mm,	Y =   -355.102  mm,	Z =   -224.956  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[734]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  292.218  mm,	Y =   -354.513  mm,	Z =   -225.830  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[735]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.895  mm,	Y =   -353.886  mm,	Z =   -225.347  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[736]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.585  mm,	Y =   -353.345  mm,	Z =   -225.316  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[737]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  291.141  mm,	Y =   -352.652  mm,	Z =   -225.865  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[738]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.864  mm,	Y =   -352.042  mm,	Z =   -224.936  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[739]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  290.103  mm,	Y =   -350.838  mm,	Z =   -225.753  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[740]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.640  mm,	Y =   -349.988  mm,	Z =   -225.398  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[741]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.363  mm,	Y =   -349.454  mm,	Z =   -225.022  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[742]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  288.977  mm,	Y =   -348.910  mm,	Z =   -225.902  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[743]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  289.007  mm,	Y =   -348.832  mm,	Z =   -224.979  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[744]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  288.598  mm,	Y =   -348.245  mm,	Z =   -225.836  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[745]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.905  mm,	Y =   -347.052  mm,	Z =   -225.898  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[746]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.856  mm,	Y =   -346.888  mm,	Z =   -225.331  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[747]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.597  mm,	Y =   -346.401  mm,	Z =   -225.057  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[748]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.465  mm,	Y =   -346.283  mm,	Z =   -225.843  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[749]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  287.067  mm,	Y =   -345.531  mm,	Z =   -225.390  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[750]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.843  mm,	Y =   -345.140  mm,	Z =   -225.369  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[751]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.413  mm,	Y =   -344.462  mm,	Z =   -225.853  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[752]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.421  mm,	Y =   -344.404  mm,	Z =   -225.339  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[753]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  286.104  mm,	Y =   -343.799  mm,	Z =   -224.934  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[754]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.703  mm,	Y =   -343.227  mm,	Z =   -225.814  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[755]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.716  mm,	Y =   -343.185  mm,	Z =   -225.352  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[756]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.021  mm,	Y =   -342.055  mm,	Z =   -225.883  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[757]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  285.006  mm,	Y =   -341.909  mm,	Z =   -225.026  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[758]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  284.638  mm,	Y =   -341.396  mm,	Z =   -225.905  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[759]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  284.542  mm,	Y =   -341.157  mm,	Z =   -225.390  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[760]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  284.260  mm,	Y =   -340.728  mm,	Z =   -225.825  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[761]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  283.947  mm,	Y =   -340.179  mm,	Z =   -225.757  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[762]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  283.943  mm,	Y =   -340.076  mm,	Z =   -225.084  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[763]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  283.652  mm,	Y =   -339.616  mm,	Z =   -225.393  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[764]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  283.491  mm,	Y =   -339.401  mm,	Z =   -225.842  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[765]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  283.214  mm,	Y =   -338.810  mm,	Z =   -225.058  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[766]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  283.095  mm,	Y =   -338.710  mm,	Z =   -225.807  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[767]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.884  mm,	Y =   -338.277  mm,	Z =   -225.332  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[768]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.774  mm,	Y =   -338.163  mm,	Z =   -225.876  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[769]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.433  mm,	Y =   -337.456  mm,	Z =   -225.052  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[770]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.371  mm,	Y =   -337.390  mm,	Z =   -225.326  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[771]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  282.036  mm,	Y =   -336.813  mm,	Z =   -225.375  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[772]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.781  mm,	Y =   -336.317  mm,	Z =   -224.967  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[773]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.391  mm,	Y =   -335.773  mm,	Z =   -225.912  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[774]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.317  mm,	Y =   -335.568  mm,	Z =   -225.365  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[775]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  281.033  mm,	Y =   -335.035  mm,	Z =   -225.072  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[776]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  280.601  mm,	Y =   -334.379  mm,	Z =   -225.726  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[777]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  280.243  mm,	Y =   -333.754  mm,	Z =   -225.695  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[778]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  279.974  mm,	Y =   -333.246  mm,	Z =   -225.385  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[779]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  279.552  mm,	Y =   -332.568  mm,	Z =   -225.775  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[780]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  279.425  mm,	Y =   -332.285  mm,	Z =   -225.323  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[781]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  279.142  mm,	Y =   -331.800  mm,	Z =   -225.363  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[782]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  278.831  mm,	Y =   -331.331  mm,	Z =   -225.853  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[783]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  278.414  mm,	Y =   -330.611  mm,	Z =   -225.873  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[784]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  278.063  mm,	Y =   -330.063  mm,	Z =   -225.851  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[785]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  277.652  mm,	Y =   -329.413  mm,	Z =   -224.975  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[786]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  276.939  mm,	Y =   -328.843  mm,	Z =   -225.875  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[787]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  276.505  mm,	Y =   -328.450  mm,	Z =   -224.928  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[788]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  276.052  mm,	Y =   -328.176  mm,	Z =   -224.961  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[789]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  275.949  mm,	Y =   -328.202  mm,	Z =   -225.686  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[790]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  275.014  mm,	Y =   -327.801  mm,	Z =   -224.980  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[791]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  274.857  mm,	Y =   -327.845  mm,	Z =   -225.925  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[792]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  273.400  mm,	Y =   -327.581  mm,	Z =   -225.074  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[793]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  273.332  mm,	Y =   -327.624  mm,	Z =   -225.606  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[794]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  271.568  mm,	Y =   -327.736  mm,	Z =   -224.950  mm,
	W =  0.235 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[795]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.476  mm,	Y =   -350.006  mm,	Z =   -225.113  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[796]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.492  mm,	Y =   -349.646  mm,	Z =   -224.949  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[797]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  254.026  mm,	Y =   -349.246  mm,	Z =   -225.294  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[798]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  253.383  mm,	Y =   -349.606  mm,	Z =   -225.773  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[799]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.761  mm,	Y =   -349.972  mm,	Z =   -225.851  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[800]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.751  mm,	Y =   -349.908  mm,	Z =   -224.994  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[801]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.413  mm,	Y =   -350.178  mm,	Z =   -225.923  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[802]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  252.163  mm,	Y =   -350.316  mm,	Z =   -225.836  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[803]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.862  mm,	Y =   -350.423  mm,	Z =   -225.010  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[804]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.518  mm,	Y =   -350.695  mm,	Z =   -225.921  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[805]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  251.231  mm,	Y =   -350.820  mm,	Z =   -225.415  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[806]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.595  mm,	Y =   -351.225  mm,	Z =   -225.884  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[807]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.354  mm,	Y =   -351.292  mm,	Z =   -224.994  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[808]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.275  mm,	Y =   -351.412  mm,	Z =   -225.913  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[809]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  250.009  mm,	Y =   -351.490  mm,	Z =   -224.981  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[810]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.644  mm,	Y =   -351.771  mm,	Z =   -225.845  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[811]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  249.076  mm,	Y =   -352.062  mm,	Z =   -225.385  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[812]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.485  mm,	Y =   -352.369  mm,	Z =   -224.958  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[813]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.437  mm,	Y =   -352.432  mm,	Z =   -225.404  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[814]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.192  mm,	Y =   -352.610  mm,	Z =   -225.858  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[815]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  248.150  mm,	Y =   -352.559  mm,	Z =   -224.927  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[816]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  247.609  mm,	Y =   -352.879  mm,	Z =   -225.011  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[817]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.915  mm,	Y =   -353.353  mm,	Z =   -225.921  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[818]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.614  mm,	Y =   -353.516  mm,	Z =   -225.791  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[819]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.352  mm,	Y =   -353.637  mm,	Z =   -225.414  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[820]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  246.063  mm,	Y =   -353.800  mm,	Z =   -225.371  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[821]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.719  mm,	Y =   -354.039  mm,	Z =   -225.870  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[822]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  245.407  mm,	Y =   -354.219  mm,	Z =   -225.868  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[823]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.785  mm,	Y =   -354.579  mm,	Z =   -225.878  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[824]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.493  mm,	Y =   -354.751  mm,	Z =   -225.915  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[825]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  244.186  mm,	Y =   -354.850  mm,	Z =   -224.944  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[826]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.580  mm,	Y =   -355.277  mm,	Z =   -225.903  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[827]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.552  mm,	Y =   -355.219  mm,	Z =   -224.989  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[828]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  243.238  mm,	Y =   -355.460  mm,	Z =   -225.728  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[829]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.979  mm,	Y =   -355.552  mm,	Z =   -225.015  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[830]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.821  mm,	Y =   -355.673  mm,	Z =   -225.377  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[831]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.654  mm,	Y =   -355.811  mm,	Z =   -225.897  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[832]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  242.346  mm,	Y =   -355.915  mm,	Z =   -224.979  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[833]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  241.135  mm,	Y =   -356.678  mm,	Z =   -225.767  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[834]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.535  mm,	Y =   -357.031  mm,	Z =   -225.858  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[835]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.184  mm,	Y =   -357.234  mm,	Z =   -225.858  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[836]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.890  mm,	Y =   -357.329  mm,	Z =   -224.933  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[837]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.840  mm,	Y =   -357.435  mm,	Z =   -225.888  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[838]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.597  mm,	Y =   -357.578  mm,	Z =   -225.914  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[839]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  239.239  mm,	Y =   -357.771  mm,	Z =   -225.755  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[840]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.979  mm,	Y =   -357.891  mm,	Z =   -225.378  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[841]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.623  mm,	Y =   -358.136  mm,	Z =   -225.867  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[842]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.325  mm,	Y =   -358.239  mm,	Z =   -225.019  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[843]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  238.318  mm,	Y =   -358.313  mm,	Z =   -225.868  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[844]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.729  mm,	Y =   -358.654  mm,	Z =   -225.883  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[845]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.335  mm,	Y =   -358.843  mm,	Z =   -225.406  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[846]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.177  mm,	Y =   -358.897  mm,	Z =   -224.947  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[847]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  237.096  mm,	Y =   -359.020  mm,	Z =   -225.901  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[848]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.510  mm,	Y =   -359.289  mm,	Z =   -225.036  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[849]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  236.258  mm,	Y =   -359.462  mm,	Z =   -225.381  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[850]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.905  mm,	Y =   -359.705  mm,	Z =   -225.865  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[851]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.867  mm,	Y =   -359.653  mm,	Z =   -224.941  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[852]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.623  mm,	Y =   -359.863  mm,	Z =   -225.803  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[853]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  235.230  mm,	Y =   -360.022  mm,	Z =   -224.967  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[854]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  234.945  mm,	Y =   -360.189  mm,	Z =   -224.993  mm,
	W =  90.000 deg,	P =   -89.765 deg,	R =   30.000 deg
};
P[855]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  225.565  mm,	Y =   -342.543  mm,	Z =   -225.473  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   30.000 deg
};
P[856]{
   GP1:
	UF : 0, UT : 6,		CONFIG : 'N U T, 0, 0, 0',
	X =  240.000  mm,	Y =   -370.000  mm,	Z =   -170.000  mm,
	W =  90.000 deg,	P =   0.000 deg,	R =   30.000 deg
};
/END
